package dev.mascwa.pulse.core.telemetry

/**
 * The offline animal catalogue — species detail + which fauna occupy each biome/continent. Content for
 * [AnimalHabitats]. Every entry is written to be actually useful in the field: identify → behaviour →
 * what to do → first aid. Regional (not a live tracker): "these inhabit this kind of country here."
 *
 * Sources are general field-guide / first-aid consensus (Red Cross / wilderness-medicine style). This is
 * survival reference, not medical advice — in any real emergency, get professional help.
 */
object AnimalCatalog {

    val ANIMALS: Map<String, Animal> = listOf(
        // ---------------- Bears ----------------
        Animal("grizzly_bear", "Grizzly / Brown Bear", AnimalKind.MAMMAL, 4, true,
            identify = "Large (250–360 kg), shoulder hump, dished face, long pale-tipped fur, 5–10 cm claws.",
            behavior = "Not usually hunting you, but fiercely defensive of cubs and food. Most attacks are surprise-defence.",
            ifEncountered = "Do NOT run (triggers chase). Speak calmly, make yourself large, back away slowly. Carry bear spray, use at ~9 m. If a brown/grizzly makes contact: PLAY DEAD — lie face-down, hands over neck, legs spread. Fight back only if the attack is prolonged/predatory.",
            firstAid = "Control bleeding with direct pressure; treat for shock; evacuate. Puncture wounds infect fast — irrigate and get antibiotics."),
        Animal("black_bear", "American Black Bear", AnimalKind.MAMMAL, 3, false,
            identify = "Smaller than grizzly, no shoulder hump, straight face profile, black to cinnamon.",
            behavior = "Usually shy and food-driven; genuine attacks rare and often predatory when they happen.",
            ifEncountered = "Stand tall, make noise, do NOT play dead. Back away; if it attacks, FIGHT BACK hard — hit the nose and eyes. Store food away from camp.",
            firstAid = "Clean and dress wounds; watch for infection; seek care."),
        Animal("polar_bear", "Polar Bear", AnimalKind.MAMMAL, 4, true,
            identify = "Huge white bear, black nose, on sea ice / arctic coast.",
            behavior = "An apex predator that WILL hunt humans — one of the few that stalks people as prey.",
            ifEncountered = "Avoid entirely. Travel armed in polar-bear country. Deterrents: flares, air-horn, firearm as last resort. Never approach; never get between one and the water.",
            firstAid = "Massive trauma likely; control catastrophic bleeding, treat for shock and cold, evacuate immediately."),
        // ---------------- Big cats & canids ----------------
        Animal("cougar", "Cougar / Mountain Lion", AnimalKind.MAMMAL, 3, true,
            identify = "Tawny, long heavy tail, up to 2.4 m nose-to-tail; rarely seen.",
            behavior = "Ambush predator. Attacks are rare but predatory — it stalks. Small/lone people and children are at higher risk.",
            ifEncountered = "Do NOT run or crouch. Face it, look big, raise arms/jacket, shout. Throw things. If attacked, fight back — protect your neck, target the eyes.",
            firstAid = "Neck/head wounds common; control bleeding, immobilise, evacuate."),
        Animal("jaguar", "Jaguar", AnimalKind.MAMMAL, 3, false,
            identify = "Stocky spotted cat with rosettes, powerful jaws; Central/South American forest & wetland.",
            behavior = "Elusive, rarely attacks humans; a threat if cornered or a mother with cubs.",
            ifEncountered = "Back away facing it, look large, do not run. Avoid dense riverbanks at dusk alone.",
            firstAid = "Deep punctures — control bleeding, prevent infection, evacuate."),
        Animal("lion", "Lion", AnimalKind.MAMMAL, 4, true,
            identify = "Large tawny cat, males maned; prides in African savanna.",
            behavior = "Apex predator; most dangerous on foot at night or near a kill/cubs.",
            ifEncountered = "Do NOT run. Stand tall in a group, make noise, back away slowly while facing it. Never turn your back. Avoid walking at dawn/dusk/night.",
            firstAid = "Catastrophic trauma; stop bleeding, treat shock, urgent evacuation."),
        Animal("leopard", "Leopard", AnimalKind.MAMMAL, 4, true,
            identify = "Rosetted cat, smaller than a jaguar; Africa & Asia, often near villages.",
            behavior = "Powerful, secretive, active at night; can be a stalking threat, especially if injured.",
            ifEncountered = "Face it, look big, make noise, retreat slowly. Do not corner it. Keep children close.",
            firstAid = "Deep bites/claws — bleeding control, infection prevention, evacuation."),
        Animal("tiger", "Tiger", AnimalKind.MAMMAL, 4, true,
            identify = "Huge orange-black striped cat; Asian forest, mangrove, grassland.",
            behavior = "Apex ambush predator; some become man-eaters. Extremely dangerous.",
            ifEncountered = "Avoid its habitat alone. If seen, do not run; back away facing it, make yourself large and loud.",
            firstAid = "Massive trauma; control bleeding, treat shock, evacuate immediately."),
        Animal("spotted_hyena", "Spotted Hyena", AnimalKind.MAMMAL, 3, true,
            identify = "Sloping back, spotted coat, powerful jaws; African savanna, active at night.",
            behavior = "Bold pack hunter/scavenger; will test sleeping or lone people at night.",
            ifEncountered = "Keep a fire at night, don't sleep in the open. Stand tall, be loud and aggressive, throw things. Never run.",
            firstAid = "Severe bites — bleeding control, aggressive wound cleaning, evacuate."),
        Animal("gray_wolf", "Gray Wolf", AnimalKind.MAMMAL, 2, false,
            identify = "Large dog-like canid, long legs, grey/black/white; northern forests & tundra.",
            behavior = "Generally avoids humans; attacks very rare. A pack near a kill or habituated wolves warrant caution.",
            ifEncountered = "Do not run. Look big, make noise, back away. Keep dogs leashed (they draw wolves).",
            firstAid = "Bites carry infection/rabies risk — wash thoroughly, seek rabies prophylaxis."),
        Animal("coyote", "Coyote", AnimalKind.MAMMAL, 1, false,
            identify = "Small slender canid, pointed ears, bushy tail; widespread in the Americas incl. cities.",
            behavior = "Usually timid; habituated urban coyotes can be bold, rarely bite adults.",
            ifEncountered = "Haze it — shout, wave arms, throw things. Don't feed. Keep pets/food secured.",
            firstAid = "Clean any bite; rabies risk — seek care."),
        Animal("dingo", "Dingo", AnimalKind.MAMMAL, 2, false,
            identify = "Lean ginger wild dog; Australia, notably Fraser Island.",
            behavior = "Wary but can be bold around people/food; occasionally bites, dangerous to small children.",
            ifEncountered = "Don't feed or run. Stand tall, face it, back away. Keep children within arm's reach.",
            firstAid = "Clean bites; watch for infection; seek care."),
        Animal("lynx", "Lynx / Bobcat", AnimalKind.MAMMAL, 1, false,
            identify = "Short-tailed spotted cat with ear tufts; northern forests.",
            behavior = "Shy, avoids people; virtually no threat unless cornered or rabid.",
            ifEncountered = "Give it space; it will leave. Don't corner it.",
            firstAid = "Rare bites — clean, watch for infection."),
        // ---------------- Large herbivores (dangerous) ----------------
        Animal("moose", "Moose", AnimalKind.MAMMAL, 3, false,
            identify = "Huge (up to 700 kg) dark long-legged deer, bulls with broad antlers; northern forests.",
            behavior = "Injures more people than bears in some areas — aggressive in rut (autumn) and cows with calves.",
            ifEncountered = "Give it wide berth. If it charges, RUN and put a tree/rock/car between you. Watch for raised hackles, pinned ears, licking lips.",
            firstAid = "Blunt trauma/stomping — treat fractures, internal injury; evacuate."),
        Animal("bison", "Bison", AnimalKind.MAMMAL, 3, false,
            identify = "Massive humped bovine; North American grassland/parks.",
            behavior = "Deceptively fast (55 km/h); gores tourists who get too close.",
            ifEncountered = "Stay 100 m away. If it raises its tail or paws, retreat. Never approach for a photo.",
            firstAid = "Goring/blunt trauma — control bleeding, treat shock, evacuate."),
        Animal("cape_buffalo", "Cape Buffalo", AnimalKind.MAMMAL, 4, true,
            identify = "Heavy black bovine, fused 'boss' horns; African savanna.",
            behavior = "One of Africa's most dangerous — unpredictable, holds grudges, charges and gores; ambushes wounded pursuers.",
            ifEncountered = "Keep well clear, especially lone old bulls. If charged, climb a sturdy tree; there's no outrunning it.",
            firstAid = "Goring — catastrophic bleeding control, urgent evacuation."),
        Animal("hippopotamus", "Hippopotamus", AnimalKind.MAMMAL, 4, true,
            identify = "Huge barrel-bodied amphibious mammal; African rivers, lakes, wetlands.",
            behavior = "Africa's deadliest large land animal — extremely territorial in water, will capsize boats and attack on land at night.",
            ifEncountered = "Never get between a hippo and water, or near calves. Keep off riverbanks at night. Give any water body a wide margin.",
            firstAid = "Crushing/severing bites — control catastrophic bleeding, treat shock, evacuate."),
        Animal("elephant", "Elephant", AnimalKind.MAMMAL, 4, true,
            identify = "Unmistakable; African (larger ears) and Asian species.",
            behavior = "Usually peaceful but a bull in musth or a protective herd will charge and trample.",
            ifEncountered = "Keep large distance. Watch for spread ears + trumpeting (threat). Retreat quietly; use terrain/vehicles as a barrier. A mock charge (ears out, trunk up) is a warning to leave NOW.",
            firstAid = "Crush trauma — treat fractures/internal injury, evacuate."),
        Animal("rhinoceros", "Rhinoceros", AnimalKind.MAMMAL, 4, false,
            identify = "Massive horned herbivore, poor eyesight; African & Asian bush.",
            behavior = "Charges when startled; black rhino especially aggressive.",
            ifEncountered = "Stay downwind and quiet. If charged, run at an angle and get behind a large tree — they turn slowly.",
            firstAid = "Goring/trampling — bleeding control, shock, evacuation."),
        Animal("wild_boar", "Wild Boar", AnimalKind.MAMMAL, 2, false,
            identify = "Bristly wild pig with tusks; Eurasia, Americas (feral hogs).",
            behavior = "Normally flees; a cornered boar or sow with piglets charges and slashes with tusks.",
            ifEncountered = "Give space, don't corner. If charged, climb something or put an obstacle between you.",
            firstAid = "Tusk lacerations — bleeding control, wound cleaning, infection watch."),
        Animal("kangaroo", "Kangaroo", AnimalKind.MAMMAL, 2, false,
            identify = "Large hopping marsupial; Australia.",
            behavior = "Usually harmless; large males can kick/box and disembowel with hind claws if cornered or fed.",
            ifEncountered = "Don't approach or feed. Back away, turn side-on, keep low; get behind cover.",
            firstAid = "Claw lacerations — control bleeding, clean, seek care."),
        Animal("cassowary", "Cassowary", AnimalKind.BIRD, 3, false,
            identify = "Large flightless bird, black body, blue neck, bony helmet, dagger inner-toe claw; NE Australia & New Guinea rainforest.",
            behavior = "Shy but powerful; kicks with a 12 cm claw that can slash open. Dangerous when fed or defending chicks.",
            ifEncountered = "Never feed. Back away slowly, keep a tree/pack between you; don't run or turn your back.",
            firstAid = "Deep slashing wounds — direct pressure, evacuate."),
        Animal("ostrich", "Ostrich", AnimalKind.BIRD, 2, false,
            identify = "Huge flightless bird; African savanna.",
            behavior = "Can be aggressive in breeding season; kicks forward with a clawed foot that can kill.",
            ifEncountered = "Keep distance; if charged, lie flat and protect your head, or put a solid barrier between you.",
            firstAid = "Kick trauma/lacerations — bleeding control, evacuate."),
        // ---------------- Snakes ----------------
        Animal("rattlesnake", "Rattlesnake", AnimalKind.REPTILE, 3, false,
            identify = "Triangular head, keeled scales, a rattle on the tail; Americas.",
            behavior = "Ambushes prey; bites in defence when stepped on or handled. Rattle = warning.",
            ifEncountered = "Freeze, locate it, back away slowly beyond striking range (~its body length). Never handle. Watch hands/feet on rocks and woodpiles.",
            firstAid = "Venomous. Keep the victim calm and still; keep the bite BELOW heart level; remove rings/watches; do NOT cut, suck, ice, or apply a tourniquet. Get to antivenom fast."),
        Animal("copperhead", "Copperhead", AnimalKind.REPTILE, 2, false,
            identify = "Coppery-tan with hourglass crossbands; eastern US woodland.",
            behavior = "Well camouflaged; bites when stepped on. Venom rarely fatal but painful.",
            ifEncountered = "Watch where you step in leaf litter; back away. Don't handle.",
            firstAid = "Same as pit-viper: calm, still, bite below heart, no tourniquet/cutting, seek antivenom."),
        Animal("cottonmouth", "Cottonmouth / Water Moccasin", AnimalKind.REPTILE, 3, false,
            identify = "Dark, thick-bodied; gapes to show a white mouth; SE US wetlands.",
            behavior = "Semi-aquatic, stands its ground; venomous bite.",
            ifEncountered = "Back away from water edges/logs where it basks. Don't corner it.",
            firstAid = "Pit-viper first aid: immobilise, keep calm, seek antivenom; no tourniquet/incision."),
        Animal("coral_snake", "Coral Snake", AnimalKind.REPTILE, 3, false,
            identify = "Red-yellow-black bands, black snout ('red touches yellow, kill a fellow'); Americas.",
            behavior = "Reclusive, rarely bites, but potent neurotoxic venom.",
            ifEncountered = "Never handle any banded snake. Leave it alone.",
            firstAid = "Neurotoxic — apply a pressure-immobilisation bandage to the whole limb, splint, keep still, urgent antivenom. Watch breathing."),
        Animal("black_mamba", "Black Mamba", AnimalKind.REPTILE, 4, false,
            identify = "Long, slender, grey-brown; inky-black mouth; sub-Saharan Africa.",
            behavior = "Fast and nervous; highly potent neurotoxic venom, bites rapidly if cornered.",
            ifEncountered = "Do NOT approach or corner. Freeze, then back away giving it an escape route.",
            firstAid = "Life-threatening neurotoxin. Pressure-immobilisation bandage, total rest, splint, evacuate NOW; assist breathing; antivenom urgently."),
        Animal("puff_adder", "Puff Adder", AnimalKind.REPTILE, 3, false,
            identify = "Thick, sandy chevron-patterned; hisses/puffs; African bush — causes the most snakebites there.",
            behavior = "Relies on camouflage, doesn't flee, bites when stepped on; cytotoxic venom.",
            ifEncountered = "Watch your feet on paths at dusk; back off if it puffs.",
            firstAid = "Cytotoxic — immobilise, keep still, do NOT apply a tight tourniquet, evacuate to antivenom."),
        Animal("indian_cobra", "Cobra", AnimalKind.REPTILE, 4, false,
            identify = "Hoods when threatened; Asia & Africa; some spit venom.",
            behavior = "Defensive display then strike; neurotoxic; spitting cobras aim for eyes.",
            ifEncountered = "Back away from a hooding snake; protect your eyes from spitters (glasses/hand).",
            firstAid = "Neurotoxic: pressure-immobilisation, splint, rest, antivenom. Venom in eyes: flush with lots of water immediately."),
        Animal("russells_viper", "Russell's Viper", AnimalKind.REPTILE, 4, false,
            identify = "Chain-pattern brown ovals; South/SE Asia farmland — a top killer.",
            behavior = "Hisses loudly, strikes hard; bites people in fields.",
            ifEncountered = "Wear boots in fields, use a light at night, back away.",
            firstAid = "Immobilise, keep still, seek antivenom urgently; monitor for bleeding/shock."),
        Animal("eastern_brown_snake", "Eastern Brown Snake", AnimalKind.REPTILE, 4, false,
            identify = "Slender, fast, tan to dark brown; Australia — a leading cause of snakebite death.",
            behavior = "Nervous and fast; potent neurotoxic/coagulant venom.",
            ifEncountered = "Freeze, let it move off; never try to kill or catch it (most bites happen then).",
            firstAid = "Pressure-immobilisation bandage over the whole limb + splint, absolute rest, call emergency services. Do NOT wash the bite (venom ID)."),
        Animal("taipan", "Taipan", AnimalKind.REPTILE, 4, false,
            identify = "Large, slender; inland taipan has the most toxic venom of any snake; Australia.",
            behavior = "Generally shy but deadly if cornered.",
            ifEncountered = "Keep well clear; back away.",
            firstAid = "Pressure-immobilisation bandage + splint, total rest, urgent evacuation/antivenom, monitor breathing."),
        Animal("fer_de_lance", "Fer-de-Lance / Terciopelo", AnimalKind.REPTILE, 4, false,
            identify = "Large pit viper, arrowhead pattern; Central/South America — causes most bites there.",
            behavior = "Irritable, well camouflaged; potent tissue-destroying venom.",
            ifEncountered = "Watch feet on trails, use a light, back away.",
            firstAid = "Immobilise, keep still, do NOT tourniquet/cut, evacuate to antivenom fast (tissue damage progresses)."),
        Animal("green_anaconda", "Green Anaconda", AnimalKind.REPTILE, 2, false,
            identify = "Enormous olive constrictor with black blotches; South American wetlands.",
            behavior = "Non-venomous; ambushes near water. Attacks on humans very rare.",
            ifEncountered = "Keep clear of the water's edge where large ones lurk; don't wade blindly.",
            firstAid = "Constriction/bite — if seized, protect airway, don't struggle wildly, cut it off the tail end."),
        Animal("reticulated_python", "Reticulated Python", AnimalKind.REPTILE, 2, false,
            identify = "Very long patterned constrictor; SE Asia forest & near villages.",
            behavior = "Non-venomous; large ones can kill by constriction, rare.",
            ifEncountered = "Give large individuals space; don't handle.",
            firstAid = "If constricted, unwrap from the tail; protect the neck/chest."),
        Animal("european_adder", "European Adder / Viper", AnimalKind.REPTILE, 2, false,
            identify = "Zigzag dorsal stripe; the only venomous snake across much of Europe.",
            behavior = "Shy, bites only if trodden on/handled; venom rarely fatal.",
            ifEncountered = "Watch your step in heath/rocks; back away.",
            firstAid = "Immobilise, keep calm, remove rings, seek medical care (antivenom for severe reactions)."),
        // ---------------- Crocodilians & lizards ----------------
        Animal("saltwater_crocodile", "Saltwater Crocodile", AnimalKind.REPTILE, 4, true,
            identify = "Largest living reptile (up to 6 m); estuaries/coast N. Australia & SE Asia.",
            behavior = "Apex ambush predator that actively takes humans; explosive lunge from water.",
            ifEncountered = "Stay several metres back from ANY tropical waterline; never swim, clean fish, or camp at the water's edge in croc country. Vary your routine at water.",
            firstAid = "Massive trauma/drowning — control catastrophic bleeding, treat shock, evacuate."),
        Animal("nile_crocodile", "Nile Crocodile", AnimalKind.REPTILE, 4, true,
            identify = "Large croc; African rivers and lakes.",
            behavior = "Responsible for many attacks; ambushes at the water's edge.",
            ifEncountered = "Keep well back from riverbanks; don't collect water at the same spot/time; never wade.",
            firstAid = "As saltwater croc — bleeding, shock, urgent evacuation."),
        Animal("american_alligator", "American Alligator", AnimalKind.REPTILE, 3, false,
            identify = "Broad rounded snout, dark; SE US wetlands.",
            behavior = "Usually avoids people; fed or nesting gators are dangerous; explosive short lunge.",
            ifEncountered = "Stay 15 m back, never feed, keep pets/children from the water edge. If it lunges, run in a straight line away (they don't pursue far).",
            firstAid = "Bites — control bleeding, aggressive wound cleaning (heavy infection risk), seek care."),
        Animal("komodo_dragon", "Komodo Dragon", AnimalKind.REPTILE, 3, true,
            identify = "Huge monitor lizard (up to 3 m); a few Indonesian islands.",
            behavior = "Ambush predator with venomous/septic bite; has killed people.",
            ifEncountered = "Never approach; keep distance, watch for them under cover. Back away, don't run in a straight predictable line near cover.",
            firstAid = "Serious bites, bleeding + infection — control bleeding, evacuate, antibiotics."),
        Animal("gila_monster", "Gila Monster", AnimalKind.REPTILE, 2, false,
            identify = "Stout black-and-orange beaded lizard; SW US/Mexico desert.",
            behavior = "Slow, only bites if handled; then clamps and chews venom in.",
            ifEncountered = "Never pick it up. Leave it alone.",
            firstAid = "If bitten, submerge/pry the jaw open to release; wash, manage pain, seek care (rarely dangerous)."),
        // ---------------- Arachnids ----------------
        Animal("black_widow", "Black Widow", AnimalKind.ARACHNID, 3, false,
            identify = "Glossy black, red hourglass underneath; in woodpiles, sheds, undersides.",
            behavior = "Shy; bites when pressed against skin. Neurotoxic venom → severe cramps.",
            ifEncountered = "Shake out shoes/gloves/bedding; wear gloves in sheds and woodpiles.",
            firstAid = "Wash, cold pack, pain relief; seek care for severe cramps/breathing trouble (antivenom exists)."),
        Animal("brown_recluse", "Brown Recluse", AnimalKind.ARACHNID, 2, false,
            identify = "Light brown, violin mark on the back; hides in undisturbed indoor clutter; central US.",
            behavior = "Bites when trapped against skin; venom can cause a slow-healing necrotic ulcer.",
            ifEncountered = "Shake out clothing/bedding; clear clutter; wear gloves in storage.",
            firstAid = "Clean, cold pack, elevate, do NOT excise; monitor the wound and seek care if it worsens."),
        Animal("funnel_web_spider", "Sydney Funnel-Web", AnimalKind.ARACHNID, 4, false,
            identify = "Large glossy black spider, fangs that bite downward; SE Australia, wanders into homes/pools.",
            behavior = "Aggressive when cornered; among the most dangerous spiders — fast-acting venom.",
            ifEncountered = "Check shoes/pool skimmers; don't handle. Keep it for ID if bitten (carefully).",
            firstAid = "Pressure-immobilisation bandage + splint (like snakebite), keep still, call emergency services — antivenom is effective."),
        Animal("redback_spider", "Redback Spider", AnimalKind.ARACHNID, 3, false,
            identify = "Black with a red dorsal stripe (a widow relative); Australia, under objects.",
            behavior = "Bites when disturbed in webs under furniture/sheds; painful venom.",
            ifEncountered = "Check under seats, bins, and stored items; wear gloves.",
            firstAid = "Do NOT bandage tightly (it's slow-acting) — apply a cold pack, pain relief, seek care (antivenom for severe cases)."),
        Animal("brazilian_wandering_spider", "Brazilian Wandering Spider", AnimalKind.ARACHNID, 4, false,
            identify = "Large brown/grey spider that roams the ground at night; hides in banana bunches, shoes; tropical S. America.",
            behavior = "Defensive, raises front legs; potent venom.",
            ifEncountered = "Shake out shoes and produce; don't reach blindly into dark spaces.",
            firstAid = "Wash, immobilise, manage pain, urgent medical care (antivenom available)."),
        Animal("deathstalker_scorpion", "Deathstalker Scorpion", AnimalKind.ARACHNID, 3, false,
            identify = "Pale yellow scorpion; N. Africa & Middle East desert.",
            behavior = "One of the most venomous scorpions; stings when disturbed.",
            ifEncountered = "Shake out boots/bedding, use a light at night, don't lift rocks bare-handed.",
            firstAid = "Cold pack, pain relief, keep calm; seek care urgently for children/severe reactions (antivenom)."),
        Animal("bark_scorpion", "Bark Scorpion", AnimalKind.ARACHNID, 2, false,
            identify = "Small pale scorpion, climbs; SW US/Mexico.",
            behavior = "Hides in shoes, bedding, wood; most medically significant US scorpion.",
            ifEncountered = "Shake out footwear/clothing; use a UV light at night (they glow).",
            firstAid = "Cold pack, pain relief; watch children closely; seek care for severe symptoms."),
        // ---------------- Insects ----------------
        Animal("mosquito", "Mosquito", AnimalKind.INSECT, 3, true,
            identify = "Tiny biting fly; worst at dawn/dusk near standing water.",
            behavior = "The deadliest animal on Earth by human toll — vectors malaria, dengue, Zika, yellow fever.",
            ifEncountered = "Cover skin, use DEET/picaridin, sleep under a treated net, drain standing water, take antimalarials where indicated.",
            firstAid = "For fever/illness days after bites in endemic areas, seek testing/treatment immediately."),
        Animal("tick", "Tick", AnimalKind.ARACHNID, 2, false,
            identify = "Tiny arachnid that latches to skin; grass/brush; transmits Lyme and other diseases.",
            behavior = "Painless bite, feeds for days; disease risk rises with attachment time.",
            ifEncountered = "Tuck trousers into socks, use repellent, check your body after brushy travel.",
            firstAid = "Remove with tweezers straight up close to the skin; disinfect; note a bullseye rash/fever and seek care."),
        Animal("africanized_bee", "Africanized 'Killer' Bee", AnimalKind.INSECT, 3, true,
            identify = "Looks like a honeybee; aggressive colonies; Americas.",
            behavior = "Defends the hive en masse, pursues 100s of metres — mass stings can kill.",
            ifEncountered = "If a swarm attacks, RUN in a straight line to enclosed shelter, protect your face; do NOT swat or jump in water (they wait).",
            firstAid = "Scrape (don't pinch) stings out; for many stings or any breathing/swelling, treat anaphylaxis (adrenaline) and get emergency help."),
        Animal("bullet_ant", "Bullet Ant", AnimalKind.INSECT, 2, false,
            identify = "Large (2.5 cm) black ant; Central/South American rainforest.",
            behavior = "Sting causes agonising pain for hours (the worst of any insect).",
            ifEncountered = "Don't grab tree trunks/vines blindly; watch where you sit.",
            firstAid = "Cold pack, pain relief; usually not dangerous unless allergic."),
        Animal("tsetse_fly", "Tsetse Fly", AnimalKind.INSECT, 2, true,
            identify = "Large biting fly; sub-Saharan Africa.",
            behavior = "Painful bite; transmits sleeping sickness (trypanosomiasis).",
            ifEncountered = "Wear neutral-coloured long clothing (they're drawn to blue/black), use repellent, avoid bush at midday.",
            firstAid = "For fever/headache after bites in endemic areas, seek testing/treatment."),
        // ---------------- Marine / coast ----------------
        Animal("great_white_shark", "Shark", AnimalKind.MARINE, 3, false,
            identify = "Large predatory fish; coastal seas worldwide.",
            behavior = "Attacks rare and usually investigatory; risk higher at dawn/dusk, in murky water, near seals/bait.",
            ifEncountered = "Don't swim at dawn/dusk or near baitfish/seals; if one is near, face it, stay vertical, back toward shore/boat calmly. If attacked, hit the eyes/gills.",
            firstAid = "Control catastrophic limb bleeding on the beach FIRST (tourniquet high and tight), treat shock, evacuate."),
        Animal("box_jellyfish", "Box Jellyfish", AnimalKind.MARINE, 4, true,
            identify = "Pale cuboid bell with long trailing tentacles; Indo-Pacific coast (esp. N. Australia, wet season).",
            behavior = "Among the most venomous animals; a bad sting can stop the heart in minutes.",
            ifEncountered = "Heed beach closures/stinger nets; wear a full stinger suit in season; don't enter the water when warned.",
            firstAid = "Douse the area with VINEGAR for 30 s (do not rub), remove tentacles, start CPR if unresponsive, call emergency — antivenom exists."),
        Animal("stonefish", "Stonefish", AnimalKind.MARINE, 3, false,
            identify = "Master-camouflaged as a rock on reef flats; Indo-Pacific shallows.",
            behavior = "Venomous dorsal spines; stepped-on stings are excruciating.",
            ifEncountered = "Wear thick-soled reef shoes, shuffle your feet, never touch 'rocks'.",
            firstAid = "Immerse the wound in HOT (not scalding) water ~30–90 min for pain, remove spines, seek care/antivenom."),
        Animal("stingray", "Stingray", AnimalKind.MARINE, 2, false,
            identify = "Flat disc-shaped ray with a barbed tail; sandy shallows worldwide.",
            behavior = "Non-aggressive; the barb stings defensively when stepped on.",
            ifEncountered = "Do the 'stingray shuffle' — slide your feet along the sand so it swims off.",
            firstAid = "Immerse in HOT water 30–90 min, control bleeding, remove visible barb fragments, seek care (chest/abdomen stings are emergencies)."),
        Animal("sea_snake", "Sea Snake", AnimalKind.MARINE, 3, false,
            identify = "Paddle-tailed snake; warm coastal Indo-Pacific waters.",
            behavior = "Usually docile; potent venom, bites if handled/netted.",
            ifEncountered = "Don't handle; shuffle in shallows; be careful hauling nets.",
            firstAid = "Pressure-immobilisation bandage, keep still, evacuate for antivenom; watch breathing."),
        // ---------------- Amphibians ----------------
        Animal("poison_dart_frog", "Poison Dart Frog", AnimalKind.AMPHIBIAN, 2, false,
            identify = "Tiny brilliantly-coloured frog; Central/South American rainforest.",
            behavior = "Toxins are in the SKIN — dangerous only if you handle it and touch your mouth/eyes/cuts.",
            ifEncountered = "Never handle brightly-coloured frogs; wash hands after any contact.",
            firstAid = "Rinse skin/eyes thoroughly; seek care if numbness/illness follows contact."),
        // ---------------- Common / harmless residents ----------------
        Animal("white_tailed_deer", "Deer", AnimalKind.MAMMAL, 1, false,
            identify = "Familiar brown deer, white tail; forests/edges worldwide.",
            behavior = "Harmless; a road hazard, and rut bucks/does with fawns rarely lash out.",
            ifEncountered = "Enjoy at a distance; don't approach fawns; drive alert at dawn/dusk.",
            firstAid = null),
        Animal("red_fox", "Red Fox", AnimalKind.MAMMAL, 0, false,
            identify = "Small russet canid, bushy white-tipped tail; near-global.",
            behavior = "Shy and harmless; nocturnal, sometimes urban.",
            ifEncountered = "Observe; don't feed; secure bins. Rabies risk only in some regions.",
            firstAid = null),
        Animal("raccoon", "Raccoon", AnimalKind.MAMMAL, 1, false,
            identify = "Grey, black facial mask, ringed tail; the Americas, urban.",
            behavior = "Clever, food-driven; bites/scratches if cornered; rabies vector.",
            ifEncountered = "Don't feed or corner; secure food/bins. A daytime, disoriented raccoon may be rabid — avoid.",
            firstAid = "Wash any bite/scratch thoroughly and seek rabies advice."),
        Animal("wild_rabbit", "Rabbit / Hare", AnimalKind.MAMMAL, 0, false,
            identify = "Small long-eared herbivore; grassland and edges worldwide.",
            behavior = "Harmless; a food source in survival situations.",
            ifEncountered = "No threat. (Cook thoroughly if trapped for food.)",
            firstAid = null),
        Animal("macaque", "Macaque Monkey", AnimalKind.MAMMAL, 1, false,
            identify = "Medium brown monkey; Asia, often around temples/towns.",
            behavior = "Bold around people/food; bites and scratches, can carry herpes-B.",
            ifEncountered = "Don't feed, make eye contact, or show teeth (a threat to them). Hide food; back away.",
            firstAid = "Wash any bite/scratch 15 min and seek medical care (disease risk)."),
        Animal("capybara", "Capybara", AnimalKind.MAMMAL, 0, false,
            identify = "Giant guinea-pig-like rodent; South American wetlands.",
            behavior = "Docile herbivore; no threat (but can carry ticks).",
            ifEncountered = "Observe at a distance.",
            firstAid = null),
        Animal("vulture", "Vulture", AnimalKind.BIRD, 0, false,
            identify = "Large soaring scavenging bird; savanna and open country.",
            behavior = "Harmless scavenger; circling vultures can indicate a carcass (and predators near it).",
            ifEncountered = "No threat; note that a kill nearby may mean predators.",
            firstAid = null),
    ).associateBy { it.id }

    // Globally-plausible fauna per biome (disease vectors + water/coast hazards that recur everywhere).
    private val GLOBAL: Map<Biome, List<String>> = mapOf(
        Biome.TROPICAL_RAINFOREST to listOf("mosquito"),
        Biome.SAVANNA to listOf("mosquito"),
        Biome.WETLAND to listOf("mosquito", "tick"),
        Biome.TEMPERATE_FOREST to listOf("tick"),
        Biome.GRASSLAND to listOf("tick"),
        Biome.COAST to listOf("great_white_shark", "stingray"),
    )

    // The real regional fauna per (continent, biome). Falls back to CONTINENT_DEFAULT + GLOBAL when absent.
    private val REGIONAL: Map<Pair<Continent, Biome>, List<String>> = mapOf(
        // North America
        (Continent.NORTH_AMERICA to Biome.TEMPERATE_FOREST) to listOf("black_bear", "cougar", "copperhead", "rattlesnake", "white_tailed_deer", "red_fox", "raccoon", "tick"),
        (Continent.NORTH_AMERICA to Biome.BOREAL_FOREST) to listOf("grizzly_bear", "black_bear", "gray_wolf", "moose", "lynx"),
        (Continent.NORTH_AMERICA to Biome.MOUNTAIN) to listOf("grizzly_bear", "black_bear", "cougar", "moose", "rattlesnake"),
        (Continent.NORTH_AMERICA to Biome.GRASSLAND) to listOf("bison", "coyote", "rattlesnake", "white_tailed_deer", "wild_rabbit", "tick"),
        (Continent.NORTH_AMERICA to Biome.DESERT) to listOf("rattlesnake", "gila_monster", "bark_scorpion", "coyote", "cougar"),
        (Continent.NORTH_AMERICA to Biome.WETLAND) to listOf("american_alligator", "cottonmouth", "black_widow", "mosquito"),
        (Continent.NORTH_AMERICA to Biome.MEDITERRANEAN) to listOf("rattlesnake", "black_widow", "cougar", "coyote", "black_bear"),
        (Continent.NORTH_AMERICA to Biome.TUNDRA) to listOf("polar_bear", "grizzly_bear", "gray_wolf"),
        (Continent.NORTH_AMERICA to Biome.POLAR) to listOf("polar_bear"),
        (Continent.NORTH_AMERICA to Biome.COAST) to listOf("great_white_shark", "stingray"),
        // South America
        (Continent.SOUTH_AMERICA to Biome.TROPICAL_RAINFOREST) to listOf("jaguar", "fer_de_lance", "brazilian_wandering_spider", "bullet_ant", "poison_dart_frog", "green_anaconda", "mosquito"),
        (Continent.SOUTH_AMERICA to Biome.SAVANNA) to listOf("jaguar", "fer_de_lance", "capybara", "mosquito"),
        (Continent.SOUTH_AMERICA to Biome.WETLAND) to listOf("green_anaconda", "jaguar", "capybara", "fer_de_lance", "mosquito"),
        (Continent.SOUTH_AMERICA to Biome.GRASSLAND) to listOf("fer_de_lance", "capybara", "wild_rabbit"),
        (Continent.SOUTH_AMERICA to Biome.MOUNTAIN) to listOf("cougar", "fer_de_lance"),
        // Africa
        (Continent.AFRICA to Biome.SAVANNA) to listOf("lion", "leopard", "spotted_hyena", "cape_buffalo", "elephant", "rhinoceros", "black_mamba", "puff_adder", "ostrich", "vulture", "mosquito"),
        (Continent.AFRICA to Biome.TROPICAL_RAINFOREST) to listOf("leopard", "elephant", "puff_adder", "indian_cobra", "mosquito"),
        (Continent.AFRICA to Biome.DESERT) to listOf("deathstalker_scorpion", "puff_adder", "indian_cobra"),
        (Continent.AFRICA to Biome.WETLAND) to listOf("hippopotamus", "nile_crocodile", "black_mamba", "mosquito"),
        (Continent.AFRICA to Biome.GRASSLAND) to listOf("lion", "cape_buffalo", "black_mamba", "ostrich", "mosquito"),
        (Continent.AFRICA to Biome.MEDITERRANEAN) to listOf("puff_adder", "deathstalker_scorpion", "wild_boar"),
        // Europe
        (Continent.EUROPE to Biome.TEMPERATE_FOREST) to listOf("wild_boar", "gray_wolf", "european_adder", "white_tailed_deer", "red_fox", "tick"),
        (Continent.EUROPE to Biome.BOREAL_FOREST) to listOf("grizzly_bear", "gray_wolf", "lynx", "moose", "european_adder"),
        (Continent.EUROPE to Biome.MOUNTAIN) to listOf("grizzly_bear", "gray_wolf", "european_adder", "wild_boar"),
        (Continent.EUROPE to Biome.MEDITERRANEAN) to listOf("european_adder", "wild_boar", "red_fox"),
        (Continent.EUROPE to Biome.GRASSLAND) to listOf("wild_boar", "red_fox", "european_adder", "tick"),
        // Asia
        (Continent.ASIA to Biome.TROPICAL_RAINFOREST) to listOf("tiger", "leopard", "reticulated_python", "indian_cobra", "macaque", "mosquito"),
        (Continent.ASIA to Biome.TEMPERATE_FOREST) to listOf("grizzly_bear", "gray_wolf", "wild_boar", "russells_viper", "macaque", "tick"),
        (Continent.ASIA to Biome.SAVANNA) to listOf("tiger", "leopard", "elephant", "russells_viper", "indian_cobra", "mosquito"),
        (Continent.ASIA to Biome.MOUNTAIN) to listOf("grizzly_bear", "leopard", "gray_wolf"),
        (Continent.ASIA to Biome.DESERT) to listOf("indian_cobra", "deathstalker_scorpion", "gray_wolf"),
        (Continent.ASIA to Biome.WETLAND) to listOf("saltwater_crocodile", "reticulated_python", "russells_viper", "mosquito"),
        (Continent.ASIA to Biome.BOREAL_FOREST) to listOf("grizzly_bear", "gray_wolf", "lynx", "moose"),
        (Continent.ASIA to Biome.COAST) to listOf("saltwater_crocodile", "box_jellyfish", "sea_snake", "stonefish", "great_white_shark"),
        // Oceania
        (Continent.OCEANIA to Biome.SAVANNA) to listOf("dingo", "eastern_brown_snake", "taipan", "kangaroo", "redback_spider"),
        (Continent.OCEANIA to Biome.DESERT) to listOf("taipan", "eastern_brown_snake", "dingo", "redback_spider", "kangaroo"),
        (Continent.OCEANIA to Biome.TROPICAL_RAINFOREST) to listOf("cassowary", "saltwater_crocodile", "eastern_brown_snake", "funnel_web_spider", "reticulated_python"),
        (Continent.OCEANIA to Biome.TEMPERATE_FOREST) to listOf("eastern_brown_snake", "funnel_web_spider", "redback_spider", "kangaroo", "dingo"),
        (Continent.OCEANIA to Biome.MEDITERRANEAN) to listOf("eastern_brown_snake", "redback_spider", "kangaroo"),
        (Continent.OCEANIA to Biome.WETLAND) to listOf("saltwater_crocodile", "eastern_brown_snake", "sea_snake"),
        (Continent.OCEANIA to Biome.COAST) to listOf("box_jellyfish", "saltwater_crocodile", "great_white_shark", "stonefish", "stingray", "sea_snake"),
    )

    // A per-continent fallback set (harmless-leaning) when a specific (continent, biome) isn't mapped.
    private val CONTINENT_DEFAULT: Map<Continent, List<String>> = mapOf(
        Continent.NORTH_AMERICA to listOf("white_tailed_deer", "red_fox", "coyote"),
        Continent.SOUTH_AMERICA to listOf("capybara", "fer_de_lance"),
        Continent.EUROPE to listOf("red_fox", "wild_boar", "white_tailed_deer"),
        Continent.AFRICA to listOf("vulture", "puff_adder"),
        Continent.ASIA to listOf("macaque", "wild_boar"),
        Continent.OCEANIA to listOf("kangaroo", "eastern_brown_snake"),
        Continent.ANTARCTICA to emptyList(),
    )

    /** The fauna ids for a region — regional list if mapped, else the continent default, plus global biome fauna. */
    fun faunaFor(biome: Biome, continent: Continent): List<String> {
        val regional = REGIONAL[continent to biome] ?: CONTINENT_DEFAULT[continent].orEmpty()
        return (regional + GLOBAL[biome].orEmpty()).distinct()
    }
}
