package dev.mascwa.pulse.core.telemetry

/**
 * A large catalog of field-survival tips for the rotating "survival tip" notifications. Kept as pure data
 * so it's testable and shared; the on-device worker walks [tip] by an ever-advancing index so every tip
 * shows before any repeats. Content is general, standard survival guidance — not a substitute for training.
 */
object SurvivalTips {

    /** The tip at [index], cycling the whole catalog (so the rotation covers everything before repeating). */
    fun tip(index: Int): String {
        if (TIPS.isEmpty()) return ""
        val i = ((index % TIPS.size) + TIPS.size) % TIPS.size
        return TIPS[i]
    }

    /** How many distinct tips are in the catalog. */
    val size: Int get() = TIPS.size

    val TIPS: List<String> = listOf(
        // --- Priorities & mindset ---
        "Rule of Threes: ~3 minutes without air, ~3 hours without shelter in harsh weather, ~3 days without water, ~3 weeks without food. Fix them in that order.",
        "When things go wrong, STOP: Stop, Think, Observe, Plan. Panic burns energy and gets people killed.",
        "Your first survival tool is your attitude. People who decide to live, live.",
        "Stay put if you're lost and someone knows your route — a stationary target is far easier to find.",
        "Before you act, ask: does this make me warmer, drier, safer, or found? If not, skip it.",
        "Protect your core temperature above almost everything else — most wilderness deaths are from exposure, not starvation.",
        "Do the hard survival work early, while you still have daylight and energy to spare.",
        "Conserve energy like it's water: move deliberately, rest often, and avoid sweating in the cold.",
        "Keep a routine and small goals — building a fire, boiling water — to keep morale and focus up.",
        "Tell someone your plan and expected return time before every trip; it turns a search from days into hours.",
        "Three of anything is the universal distress signal: three whistle blasts, three fires, three flashes.",
        "Fear is fuel if you channel it into tasks. Name the threat, then do the next useful thing.",
        "Don't travel at night in unknown terrain — a twisted ankle in the dark can be a death sentence.",
        "Carry the survival essentials on your body, not just in your pack — packs get lost, dropped, or swept away.",
        "Check your gear and re-tie your boots at every rest stop; small failures compound in the field.",

        // --- Water & hydration ---
        "Assume all wild water carries pathogens and purify it — even a clear, cold mountain stream can carry giardia.",
        "A rolling boil for 1 full minute makes water safe; boil 3 minutes above ~2,000 m (6,500 ft).",
        "If you can't boil, chemical tablets or 2–4% unscented household bleach (2 drops per litre, wait 30 min) will disinfect clear water.",
        "Cloudy water? Filter it through cloth or let it settle first — purification works far better on clear water.",
        "Rain caught straight from the sky is generally safe to drink without treatment.",
        "Collect dew at dawn by dragging a clean cloth over grass, then wring it into a container.",
        "A transpiration bag — a clear plastic bag tied over a leafy branch in the sun — drips out clean water from the plant.",
        "In a dry riverbed, dig at the outside of the bends and lowest points; water lingers there longest.",
        "Ration sweat, not water — work in the cool hours and drink when thirsty instead of hoarding it.",
        "Pale straw-coloured urine means you're hydrated; dark yellow means drink more, now.",
        "Don't eat if you can't drink — digestion pulls water from your body and speeds dehydration.",
        "Never drink seawater or urine; the salt load dehydrates you faster than drinking nothing.",
        "Melt snow before eating it — eating snow cold drops your core temperature and costs precious heat.",
        "Follow converging animal trails downhill; they often funnel toward water.",
        "Green vegetation and swarms of insects at dawn or dusk are signs water is near.",
        "A solar still (a pit, plastic sheet, and cup) can wring drinkable water from damp ground or vegetation.",
        "Store water in the shade and keep containers capped — heat and open air speed evaporation and spoilage.",
        "Sip steadily rather than gulping a huge amount at once; your body absorbs it better.",
        "Fast-moving water over rocks is usually safer than still, stagnant pools — but still purify it.",
        "Coconut water and the moisture in many fruits count toward hydration in a pinch.",

        // --- Fire ---
        "Gather far more tinder, kindling, and fuel than you think you need before you strike a single spark.",
        "Build your fire lay small first — pencil-lead to pencil to thumb to wrist thickness — and add fuel gradually.",
        "Keep tinder bone dry: birch bark, dead-dry grass, cattail fluff, char cloth, and pine resin catch a spark best.",
        "Cotton balls smeared with petroleum jelly are a compact, near-foolproof fire starter — carry a few.",
        "Split wood burns easier than round — the dry inner faces catch faster than weathered bark.",
        "Dead branches still attached to a tree are usually drier than wood lying on the wet ground.",
        "Shield a new flame from wind and drips; a tiny fire dies from a single gust or drop.",
        "A fire needs three things — heat, fuel, oxygen; if it's struggling, one of them is missing.",
        "Lay a base of dry sticks or bark under your fire so it doesn't drown in wet or snowy ground.",
        "A ferrocerium rod works wet and lasts thousands of strikes — a better survival fire tool than matches.",
        "Feather sticks (curls shaved into dry wood) catch a spark when you have no fine tinder.",
        "Bank a fire for the night: cover the coals with ash to keep them alive until morning.",
        "Reflect heat into your shelter with a wall of logs or rocks behind the fire.",
        "Never build a fire under snow-laden branches — the melt will put it out or dump on you.",
        "Keep a fire small and feed it steadily; a bonfire wastes fuel and pushes you back from its warmth.",
        "Green or wet wood on a hot fire makes thick smoke — useful for a daytime rescue signal.",
        "Carry three ways to make fire (e.g. lighter, ferro rod, matches) and keep them in separate places.",
        "A magnifying lens, glasses, or even a clear water-filled bag can focus sunlight to an ember.",
        "Char cloth catches the faintest spark — make it by heating cotton in a near-sealed tin over coals.",
        "Put your fire out cold: drench, stir, and drench again until the ashes are cool to the touch.",

        // --- Shelter & warmth ---
        "Get off the ground — the earth steals more heat from you than cold air does. Insulate underneath first.",
        "Small shelters are warm shelters; build one just big enough to lie in, not a room.",
        "Pile a thick bed of dry leaves, grass, or boughs — at least a hand-span deep once compressed.",
        "A simple lean-to angled against the wind, with a debris pile for insulation, can save your life overnight.",
        "In snow, a quinzhee or snow cave stays near 0 °C (32 °F) inside even when it's far colder out.",
        "Poke a ventilation hole in any snow shelter — trapped exhaled air and stove fumes can suffocate you.",
        "Site your shelter away from dead trees, loose rock, dry creek beds, and lone lightning-magnet trees.",
        "Face a shelter opening away from prevailing wind, and toward a heat source like a fire and reflector.",
        "Trapped air is insulation — loose, lofted layers keep you warmer than one thick compressed layer.",
        "Stuff dry leaves or grass between your clothing layers for emergency insulation.",
        "Cover your head and neck; you lose significant heat from an exposed head in the cold.",
        "Stay dry above all in the cold — wet clothing can conduct heat away up to 25× faster than dry.",
        "A space blanket reflects your body heat back; wear it against a base layer, not over a bulky coat.",
        "In heat, build shade with a raised tarp and airflow beneath it — trap shade, not hot air.",
        "Dig down a few inches for a cooler sleeping surface in the desert; the surface bakes, the subsurface is milder.",
        "Rig your tarp taut with a ridgeline and stake the corners low to shed wind and rain.",
        "Beware cold-air sinks — valley bottoms and hollows collect the coldest air at night; camp a little higher.",
        "A candle or small lamp can noticeably warm a tiny snow shelter — but keep that vent open.",
        "Change into dry socks before sleeping; cold, damp feet ruin sleep and risk frostbite.",
        "Boil water and put it in a hard bottle inside your sleeping bag for hours of radiant warmth.",

        // --- Cold-weather survival ---
        "Watch for the umbles — stumbles, mumbles, fumbles, grumbles — they're early signs of hypothermia.",
        "Treat mild hypothermia with dry insulation, warm sweet drinks, shelter, and gentle movement — not a hot bath.",
        "Don't rub frostbitten skin or thaw it if it might refreeze — refreezing causes far worse damage.",
        "Rewarm frostbite in water at body temperature (about 37–39 °C / 99–102 °F), never over direct heat.",
        "Layer for cold: a wicking base, an insulating mid, and a wind/waterproof shell — adjust to avoid sweating.",
        "Cotton kills in the cold — once wet it stops insulating; choose wool or synthetics.",
        "Eat and drink often in the cold; your body burns fuel fast to make heat.",
        "Keep moving gently if you can't get warm, but stop before you sweat — wet layers freeze you.",
        "Windchill is the real killer; a modest breeze on bare skin multiplies heat loss dramatically.",
        "Warm your core first, then extremities — cold blood rushing back from limbs can shock the heart.",
        "Vent before you sweat: open zips and shed a layer on the climb, add it back at the rest.",
        "Keep spare batteries and lighters warm in an inner pocket — cold saps both.",
        "Frost-nipped fingers or toes: warm them against your own belly or armpits.",
        "Snow blindness is real — improvise slit goggles from bark, cardboard, or duct tape in bright snow.",
        "Break trail in soft snow in short shifts and rotate; postholing exhausts you fast.",

        // --- Hot & desert survival ---
        "In the desert, travel at dawn, dusk, or night — never in the peak heat of the day.",
        "Stay covered up in extreme sun; loose, light clothing shades you and slows sweat loss.",
        "Rest in shade and minimise exertion during peak heat; a still body needs far less water.",
        "Signs of heat exhaustion — heavy sweat, weakness, nausea — mean stop, shade, and sip water now.",
        "Heat stroke (hot, red skin, confusion, no sweat) is a life-threatening emergency — cool the body fast, however you can.",
        "Don't lie directly on hot sand or rock; put insulation between you and the ground.",
        "Keep your mouth shut and breathe through your nose to cut moisture loss in dry heat.",
        "Wet a cloth and drape it on your neck and wrists to cool the blood near the surface.",
        "Sand is coldest and firmest to travel on at night; save daylight hours for shade and rest.",
        "Salt matters in the heat — replace it with food or a pinch in water, or cramps and worse follow.",

        // --- First aid & injury ---
        "Stop severe bleeding first: firm direct pressure with a clean cloth, and keep pressing — don't peek.",
        "For life-threatening limb bleeding that won't stop, a tourniquet 5–7 cm above the wound (not on a joint) can save a life; note the time.",
        "Check the ABCs — Airway, Breathing, Circulation — before treating lesser injuries.",
        "Treat for shock: lay the person down, keep them warm, reassure them, and elevate the legs if no spinal injury.",
        "Clean a wound with the cleanest water you have; flush out debris to prevent infection.",
        "Cover wounds to keep them clean; watch for spreading redness, heat, swelling, or pus — signs of infection.",
        "Immobilise a suspected fracture as you found it; splint above and below the break, and check circulation past it.",
        "For a sprain, remember RICE: Rest, Ice, Compression, Elevation.",
        "Never move someone with a suspected spine or neck injury unless they're in immediate danger.",
        "Burns: cool with clean running water for 20 minutes, don't pop blisters, and cover loosely.",
        "For choking in a conscious adult, give firm abdominal thrusts (the Heimlich) until the object clears.",
        "Learn hands-only CPR: push hard and fast in the centre of the chest, ~100–120 per minute, until help arrives.",
        "Keep a blister from forming: tape or moleskin the hot spot the instant you feel it, before it breaks.",
        "Drain a painful blister at the edge with a sterilised needle, leave the roof on, and cover it.",
        "Dehydration and low blood sugar cause bad decisions — eat, drink, and rest before big choices.",
        "Rehydrate steadily with small sips; a pinch of salt and sugar in water helps you absorb it.",
        "For a snakebite, keep the limb still and below heart level, stay calm, and get to help — no cutting, sucking, or tourniquets.",
        "Remove a tick straight out with tweezers close to the skin; don't twist or burn it.",
        "Protect a head-injured person and watch for worsening confusion, vomiting, or unequal pupils — get help.",
        "Keep a small first-aid kit and actually know how to use each item before you need it.",

        // --- Food & foraging ---
        "You can go weeks without food — don't risk poisoning yourself foraging unknown plants to fill your belly early.",
        "Never eat a wild plant, mushroom, or berry you can't identify with total certainty.",
        "White and yellow berries are mostly to be avoided; about half of red berries are edible; blue and black are more often safe — but ID before eating.",
        "Avoid plants with milky sap, thorns, a bitter or soapy taste, or a three-leaf pattern.",
        "Cook wild meat, fish, and eggs thoroughly to kill parasites and bacteria.",
        "Insects are survival protein: avoid brightly coloured, hairy, or foul-smelling ones, and cook them.",
        "Fishing is high-yield for low effort — improvise a line, hook, and set lines while you do other tasks.",
        "Set multiple snares and traps and let them work for you while you rest — trapping beats hunting for calories spent.",
        "Freshwater fish, most grubs, and cooked cattail roots are reliable wilderness food in many regions.",
        "The inner bark (cambium) of pines and some other trees is edible in an emergency.",
        "Don't eat if water is scarce — protein especially costs water to digest.",
        "Cattail is a four-season pantry: roots, shoots, and pollen are all edible when cooked or prepared.",
        "Gut and bleed game promptly and keep meat cool and covered to slow spoilage.",
        "Acorns are food only after leaching out the bitter tannins with repeated changes of water.",
        "Dandelions — leaves, roots, and flowers — are edible and widespread; a safe forage to learn first.",

        // --- Navigation & finding your way ---
        "A stick's shadow moves west to east; mark the tip, wait 15 minutes, mark again — the line runs roughly east–west.",
        "In the Northern Hemisphere, find Polaris (the North Star) off the Big Dipper's pointer stars — it marks true north.",
        "In the Southern Hemisphere, use the Southern Cross to find south.",
        "The sun rises in the east and sets in the west — a rough but reliable heading check.",
        "Moss does NOT reliably grow on the north side — don't bet your life on that myth.",
        "Follow water downhill; streams lead to rivers, rivers to people.",
        "Pick a distant landmark and walk to it in a straight line to avoid circling in featureless terrain.",
        "Note back-bearings and look behind you often — the return trail looks different than the way in.",
        "A wristwatch can approximate direction: point the hour hand at the sun and bisect the angle to 12.",
        "Trust a map and compass over your gut; lost people routinely feel certain and are wrong.",
        "Ridgelines give you the view and easier travel; valley bottoms give you water but harder going.",
        "Count your paces to estimate distance travelled, and pick handrails (a river, ridge, or road) to follow.",
        "If truly lost, climb to a high point once to get your bearings — then decide to stay put or move.",
        "Mark your route as you go with cairns, blazes, or arrows so you can retrace it.",
        "At night, keep the same star ahead of you and adjust as it drifts to hold a heading.",

        // --- Signaling & rescue ---
        "Three of anything signals distress: three fires in a triangle, three whistle blasts, three flashes.",
        "A signal mirror can flash rescuers many kilometres away — aim the bright spot at aircraft and searchers.",
        "Ground-to-air signals: a large 'V' means need assistance, an 'X' means need medical help — make them huge and high-contrast.",
        "Make signals big, geometric, and contrasting — nothing in nature is a straight line or perfect circle.",
        "A whistle carries far further than your voice and costs almost no energy — carry one, use bursts of three.",
        "Green wood or leaves on a hot fire make white smoke; a rag soaked in oil makes black — both stand out.",
        "Lay signals in open ground — a clearing, ridge, sandbar, or snowfield — where they're visible from the air.",
        "Movement catches the eye: wave bright fabric, not just hold it.",
        "Keep a charged phone off or in low-power mode and try for signal from high ground periodically.",
        "Stay near your disabled vehicle or aircraft — it's a much bigger, more visible target than a person.",
        "A flashlight or headlamp flashed in threes at night is a strong signal to aircraft and searchers.",
        "Write large messages in the sand, snow, or with rocks and logs stating who and where you are.",

        // --- Weather ---
        "Red sky at night, sailor's delight; red sky at morning, take warning — high dawn colour often precedes bad weather.",
        "A sudden drop in temperature, rising wind, and darkening towering clouds mean a storm is coming — shelter up.",
        "Halos around the sun or moon often warn of rain or snow within a day.",
        "If you can count under 30 seconds between lightning and thunder, the storm is within ~10 km — take cover.",
        "In a lightning storm, get off high ground and away from lone trees and water; crouch low, feet together.",
        "Fast-moving, low, dark clouds mean wind and weather are changing quickly — reassess your plan.",
        "Dew or frost at dawn usually means a fair day; a dry, warm night can precede rain.",
        "Falling temperatures with rising humidity often precede precipitation.",
        "Watch the wind shift — a swing to the west or north often clears weather; to the south or east often worsens it.",
        "Build and stock your shelter before bad weather arrives, not during it.",

        // --- Wildlife & insects ---
        "Most animals want nothing to do with you — make noise on the trail so you don't surprise them.",
        "Never get between a mother and her young, or corner any wild animal.",
        "Store food away from your shelter and hang it high in bear country; keep a clean camp.",
        "Back away slowly from a large predator; don't run — running triggers a chase.",
        "For a bear, generally make yourself big and loud for black bears; play dead for a defensive grizzly — know your species.",
        "Check yourself for ticks daily in tick country, especially warm, hidden areas.",
        "Shake out boots, clothing, and bedding in scorpion or snake country before putting them on.",
        "Give snakes space and a path to leave; most bites happen when people try to handle or kill them.",
        "Mosquito nets and covering up at dawn and dusk prevent bites and the diseases they carry.",
        "Don't feed wildlife — a fed animal becomes a bold, dangerous one.",

        // --- Knots, tools & gear ---
        "Learn a handful of knots cold: bowline (fixed loop), taut-line hitch (adjustable), clove hitch, and square knot.",
        "A bowline makes a loop that won't slip or jam — good for rescue and rigging.",
        "The taut-line hitch lets you tension and slide a guy line — perfect for tarps and tents.",
        "A knife is your most versatile tool; keep it sharp, and cut away from your body.",
        "Batoning — splitting wood by tapping your knife through it with a stick — gets you to dry inner wood.",
        "Duct tape fixes gear, seals blisters, and reinforces a shelter — wrap some around your bottle or lighter.",
        "Paracord's inner strands become fishing line, snares, or sewing thread — one cord is many tools.",
        "Keep a small repair kit: needle, strong thread, safety pins, wire, and tape.",
        "Dry your gear whenever the sun comes out; damp gear fails when you need it most.",
        "A metal container lets you boil water and cook — carry a single-wall metal bottle or cup.",

        // --- Terrain & travel ---
        "Cross a swift river at a wide, shallow, calmer stretch — never at a narrow, fast, deep one.",
        "Unbuckle your pack's hip belt before crossing water so you can shed it if you fall.",
        "Face upstream and side-step across, using a sturdy stick as a third leg for balance.",
        "Test each step on ice, scree, or a log; three points of contact keeps you upright.",
        "Kick steps and use the edges of your boots on steep snow; don't hurry a slope.",
        "Descend switchbacks rather than straight down — it's easier on your knees and far safer.",
        "Avoid avalanche terrain (steep, snow-loaded slopes) after heavy snow or rapid warming.",
        "Rest the moment you feel a hot spot on your foot — stopping now saves a crippling blister later.",
        "Keep your weight over your feet on descents; leaning back sends them sliding out.",
        "Travel the ridges to see and be seen, the valleys to find water — choose for your priority.",

        // --- Health & hygiene ---
        "Wash your hands (or use a clean cloth and water) before eating and after relieving yourself — field illness disables you fast.",
        "Dig a cat-hole for waste at least 60 m (200 ft) from water, camp, and trails, and bury it.",
        "Keep your feet clean and dry, and air them at rest stops — foot rot ends journeys.",
        "Brush your teeth with a frayed twig if you must; oral infections are miserable in the field.",
        "Protect your eyes from sun and glare; damaged eyes make everything else harder.",
        "Rest is a survival skill — fatigue causes the mistakes that turn a bad day into a disaster.",
        "Keep small cuts clean and covered; infection from a trivial wound can become life-threatening.",
        "Change and dry your socks daily, and treat trench foot by warming, drying, and elevating the feet.",
        "Manage morale like a resource — eat, warm up, and sleep before you tackle the hardest problem.",
        "Ration your effort as carefully as your food and water; steady beats fast-then-collapsed.",

        // --- Urban & disaster preparedness ---
        "Keep a go-bag ready: water, food, first aid, flashlight, radio, meds, cash, and copies of documents.",
        "Store at least 4 litres (1 gallon) of water per person per day, for a minimum of three days.",
        "In an earthquake, drop, cover, and hold on under sturdy furniture — most injuries come from falling objects.",
        "Know how to shut off your home's gas, water, and electricity before an emergency, not during one.",
        "Keep a battery or hand-crank radio to hear official information when the power and cell networks fail.",
        "Agree on a family meeting point and an out-of-area contact everyone can call after a disaster.",
        "Never run a generator, grill, or camp stove indoors — carbon monoxide is silent and deadly.",
        "Keep your vehicle's tank at least half full and a winter kit in the trunk during cold months.",
        "During a flood, turn around, don't drown — 30 cm (1 foot) of moving water can float a car.",
        "Charge power banks and devices before a forecast storm, and know your building's exits.",
        "Keep sturdy shoes and a flashlight by your bed for a night-time emergency.",
        "In a building fire, stay low under the smoke, feel doors for heat before opening, and get out — don't gather belongings.",
        "Learn your area's real hazards — flood, quake, wildfire, storm — and prepare specifically for them.",
        "Rotate stored water and food every six months so your supplies stay fresh.",
        "Keep a written list of emergency numbers and medications; phones die, paper doesn't.",

        // --- More field wisdom ---
        "Improvise a compass: magnetise a needle by stroking it on silk or hair, float it on a leaf in still water.",
        "A clear plastic bag over your feet inside your socks (a vapour barrier) keeps boots dry in deep cold.",
        "Keep your sleeping insulation dry all day so you have a warm, dry bed at night, whatever happens.",
        "Pee before you get into your sleeping bag — your body wastes heat keeping a full bladder warm.",
        "Eat a snack before bed in the cold; the digestion generates heat through the night.",
        "Carry a small mirror and whistle at all times — the two lightest, most effective signalling tools there are.",
        "Waterproof your matches by dipping the heads in wax, or carry them in a sealed container.",
        "Learn one primitive fire method (bow drill) before you need it — it's far harder than it looks.",
        "A poncho or tarp is a shelter, a rain catch, a ground sheet, and a stretcher — carry one everywhere.",
        "Keep your knife, fire, and water tools on a lanyard or in a fixed pocket so a spill can't take them.",
        "Dry tinder lives in your pocket, not your pack — body heat and a sealed bag keep it ready.",
        "Mark north on your map and orient it to the land before you plan a single step.",
        "Practice your skills at home in good weather; the field in bad weather is the wrong classroom.",
        "Water first, fire second, shelter and signal always — but let the weather set your true priority.",
        "Keep calm, keep warm, keep hydrated, keep found — the four keeps carry most people home.",
        "When you fix a problem, look up and reassess the whole situation before starting the next task.",
        "Two is one and one is none — carry a backup of anything your life depends on.",
        "Leave word, carry the ten essentials, and turn back early — most survival situations are prevented, not survived.",
        "Sanitise your hands before treating any wound, including your own — infection is the slow killer.",
        "Keep your head: almost every wilderness emergency is survivable if you slow down and think it through.",

        // --- More water & purification ---
        "SODIS: leave clear water in a clean, clear plastic bottle in full sun for at least 6 hours to disinfect it.",
        "Charcoal from your fire, crushed, can help filter sediment and odours before you purify water.",
        "Snow and ice are safer melted and boiled — sea ice more than a year old is low-salt but still purify it.",
        "A bandana pre-filter over your bottle mouth keeps out leaves and grit that clog real filters.",
        "The clearest water in a marsh is often just below the surface, away from the muddy bottom.",
        "Tie a cloth around your ankles and walk through dewy grass at dawn, then wring the water out.",
        "Cut a 'V' notch into a leaning tree or vine and hang a container to catch its dripping sap or water.",
        "Purify, then let boiled water cool with the lid on; pouring it between containers adds oxygen and improves the taste.",

        // --- More fire & heat ---
        "A Dakota fire hole — two connected pits — burns hot, hides the flame, and resists wind.",
        "Fatwood (resin-soaked pine heartwood) lights even when damp — shave it for tinder.",
        "Keep your fire lay under an overhang or lean-to in the rain, and stockpile dry fuel beneath cover.",
        "A single candle inside a tin can with holes makes a compact, wind-resistant heater and cook flame.",
        "Steel wool touched to a 9-volt battery bursts into sparks — an emergency fire starter worth knowing.",
        "Rotate wet fuel around the edge of a fire to dry it before it's your turn to burn.",
        "Build a long-log 'self-feeding' fire so two big logs slowly burn toward each other through the night.",

        // --- More shelter, cold & heat ---
        "In wind, a low A-frame or a snow trench beats a tall shelter that the gale tears at.",
        "Wear a hat to bed — a surprising amount of overnight warmth is kept or lost at the head.",
        "Elevate a sleeping platform off cold or wet ground with logs and a lattice of boughs.",
        "Loosen tight boots and clothing in the cold — constriction cuts circulation and invites frostbite.",
        "In the desert, two layers of clothing with an air gap can be cooler than one, and cut water loss.",
        "Bury water bottles a hand's depth in shaded sand to keep them cool through a desert day.",
        "Shivering is your body making heat — feed it: add layers, get out of the wind, and drink something warm.",
        "Keep tomorrow's socks and base layer in your sleeping bag so they're warm and dry to put on.",

        // --- More first aid ---
        "Pack a deep wound with clean gauze or cloth and press hard if direct pressure alone won't stop the bleed.",
        "Elevate a bleeding limb above the heart while you keep pressure on it.",
        "For a nosebleed, lean forward and pinch the soft part of the nose for 10 unbroken minutes.",
        "Flush a chemical or grit injury to the eye with clean water for many minutes, from the nose side outward.",
        "Suspect internal injury after a hard fall or blow — treat gently, watch for shock, and get help.",
        "Keep an impaled object in place and pad around it; pulling it out can cause fatal bleeding.",
        "Rewarm a cold-water near-drowning victim gently and get medical help — they can worsen hours later.",
        "For heat cramps, rest in shade, sip water with a little salt, and gently stretch the muscle.",
        "Splint a broken finger to the one beside it as a quick, effective field fix.",
        "Watch a burn for infection over the next days — increasing pain, redness, and pus mean trouble.",
        "Carry any personal life-saving meds (inhaler, EpiPen, insulin) in a known, quick-access spot.",
        "A triangular bandage is a sling, a tourniquet pad, a dressing, and a wrap — learn its uses.",

        // --- More plants, food & fishing ---
        "The Universal Edibility Test is a slow last resort — contact, taste, then wait hours between steps; never rush it.",
        "Avoid any mushroom you can't name — there is no reliable rule of thumb that keeps you safe.",
        "Nettles are a nutritious green once boiled, which destroys their sting.",
        "Grasshoppers and crickets are good protein — remove legs and wings, and always cook them.",
        "Set a fish trap or funnel of stones in a stream inlet and let the current bring you dinner.",
        "Clams and mussels can be dangerous when the water is warm or there's a red tide — cook and be cautious.",
        "Plantain (the broadleaf weed) and dandelion are common, safe wild greens to learn first.",
        "Roast pine nuts and acorns (leached) for calories, and chew pine needles for a vitamin-C tea.",
        "Check snares and lines at dawn and dusk when animals move most.",
        "Salt, smoke, or dry surplus meat and fish in thin strips to preserve it for lean days.",

        // --- More navigation & signalling ---
        "Orient your map to the terrain first — line up a visible ridge or river before choosing a route.",
        "In fog or whiteout, stop; moving blind invites cliffs, drop-offs, and going in circles.",
        "A phone's compass and offline maps work without signal — download the area before you go.",
        "Leave a note or arrow at every decision point so searchers (and you) can follow your path.",
        "The lower a star sits after you sight it, the more it has drifted — re-pick a fresh guide star.",
        "Flash a mirror by making a 'V' with your fingers, sighting the target through it, and flashing across your fingertips.",
        "An aircraft is most likely to spot you against contrast — a dark signal on snow, a bright one on dark ground.",
        "Keep a signal ready to trigger fast — a rescue plane may be overhead for only seconds.",

        // --- More weather, terrain & mindset ---
        "Cumulus clouds building into tall anvils by afternoon warn of thunderstorms — plan to be sheltered.",
        "When thunder roars, go indoors or low; if caught out, avoid ridges, lone trees, and open water.",
        "Turn back when the weather, the light, or the group's energy turns — summits and shortcuts aren't worth a rescue.",
        "Test a snow bridge or ice edge with your pole before you trust it with your weight.",
        "On loose scree, plant your feet flat and take small steps; a slide here breaks ankles.",
        "Fatigue, cold, hunger, and fear each cloud judgement — fix them before you make a big call.",
        "Break a huge problem into the next small task: get warm, get water, get found — one at a time.",
        "Hope is a plan plus action; pick a task you can finish and do it now.",
        "Rehearse your emergency steps out loud — under stress you'll fall back to what you've practised.",
        "Keep a positive, useful thought going; the mind quits long before the body has to.",
    )
}
