package dev.mascwa.pulse.core.telemetry

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Expected geometry generated by an independent implementation rather than by restating this
 * one's arithmetic — otherwise a sign error would simply be asserted to be correct.
 */
class CpaTest {

    private fun track(
        id: String,
        lat: Double,
        lon: Double,
        speedMs: Double,
        trackDeg: Double,
        altitudeM: Double? = null,
        verticalRateMs: Double = 0.0,
    ) = Cpa.Track(id, id, lat, lon, altitudeM, speedMs, trackDeg, verticalRateMs)

    @Test fun headOnTracksMeetAtZeroSeparation() {
        // 20 km apart on one meridian, closing at 100 m/s each.
        val north = track("N", 40.0, -74.0, 100.0, 0.0)
        val south = track("S", 40.1798, -74.0, 100.0, 180.0)
        val approach = Cpa.approach(north, south)
        assertNotNull(approach)
        approach!!
        assertEquals(99.9644, approach.secondsToClosest, 0.01)
        assertEquals(0.0, approach.closestHorizontalM, 1.0)
        assertEquals(19992.8754, approach.currentHorizontalM, 1.0)
        assertTrue(approach.converging)
    }

    @Test fun crossingTracksClosestApproachIsNotZero() {
        val eastbound = track("E", 40.0, -74.0, 100.0, 90.0)
        val southbound = track("S", 40.0899, -74.0, 100.0, 180.0)
        val approach = Cpa.approach(eastbound, southbound)!!
        assertEquals(49.9822, approach.secondsToClosest, 0.01)
        assertEquals(7068.5489, approach.closestHorizontalM, 1.0)
        assertEquals(9996.4377, approach.currentHorizontalM, 1.0)
    }

    @Test fun tracksAlreadyOpeningReportNowAsTheirClosest() {
        // Both northbound, the leader faster: the gap only grows from here.
        val trailing = track("T", 40.0, -74.0, 100.0, 0.0)
        val leading = track("L", 40.0899, -74.0, 200.0, 0.0)
        val approach = Cpa.approach(trailing, leading)!!
        assertEquals(0.0, approach.secondsToClosest, 1e-9)
        assertEquals(approach.currentHorizontalM, approach.closestHorizontalM, 1e-6)
        assertFalse("diverging tracks must not read as converging", approach.converging)
        assertFalse(approach.isNotable)
    }

    @Test fun parallelTracksAtOneSpeedNeverConverge() {
        val a = track("A", 40.0, -74.0, 150.0, 45.0)
        val b = track("B", 40.0899, -74.0, 150.0, 45.0)
        val approach = Cpa.approach(a, b)!!
        assertEquals(0.0, approach.secondsToClosest, 1e-9)
        assertEquals(9996.4377, approach.closestHorizontalM, 1.0)
        assertFalse(approach.converging)
    }

    @Test fun verticalSeparationDecidesWhetherAConvergenceIsNotable() {
        // Same head-on geometry, so they meet horizontally. Only the altitudes differ.
        val lowLevel = track("LOW", 40.0, -74.0, 100.0, 0.0, altitudeM = 3000.0)
        val alsoLow = track("LOW2", 40.1798, -74.0, 100.0, 180.0, altitudeM = 3050.0)
        assertTrue(Cpa.approach(lowLevel, alsoLow)!!.isNotable)

        // A thousand metres apart vertically is routine and must not be flagged.
        val highAbove = track("HIGH", 40.1798, -74.0, 100.0, 180.0, altitudeM = 4200.0)
        val separated = Cpa.approach(lowLevel, highAbove)!!
        assertEquals(1200.0, separated.closestVerticalM!!, 1.0)
        assertFalse("1200 m of separation is not a conflict", separated.isNotable)

        // Climb rates are projected forward: this one climbs into the other's level.
        val climbing = track("CLB", 40.1798, -74.0, 100.0, 180.0, altitudeM = 2000.0, verticalRateMs = 10.0)
        val converging = Cpa.approach(lowLevel, climbing)!!
        assertTrue("started 1000 m below and climbing", converging.currentVerticalM!! > 900.0)
        assertTrue("must close vertically by the meeting point", converging.closestVerticalM!! < 100.0)
        assertTrue(converging.isNotable)
    }

    @Test fun anUnknownAltitudeIsNeverTreatedAsZeroSeparation() {
        val known = track("KNOWN", 40.0, -74.0, 100.0, 0.0, altitudeM = 3000.0)
        val unknown = track("UNKNOWN", 40.1798, -74.0, 100.0, 180.0, altitudeM = null)
        val approach = Cpa.approach(known, unknown)!!
        assertNull("vertical separation is unknown, not zero", approach.closestVerticalM)
        assertNull(approach.currentVerticalM)
        // Proximity alone still qualifies, so the caller can say the vertical gap is unknown.
        assertTrue(approach.isNotable)
    }

    @Test fun degenerateInputsReturnNothing() {
        val a = track("A", 40.0, -74.0, 100.0, 0.0)
        assertNull("a contact cannot approach itself", Cpa.approach(a, a))
        assertNull(Cpa.approach(a, track("B", Double.NaN, -74.0, 100.0, 0.0)))
    }

    @Test fun theSweepExcludesParkedContactsAndOrdersByTime() {
        val tracks = listOf(
            track("FAR", 41.5, -74.0, 100.0, 180.0, altitudeM = 3000.0),
            track("NEAR_A", 40.0, -74.0, 100.0, 0.0, altitudeM = 3000.0),
            track("NEAR_B", 40.1798, -74.0, 100.0, 180.0, altitudeM = 3000.0),
            // Parked on a stand: its reported heading is meaningless and must not be extrapolated.
            track("PARKED", 40.05, -74.0, 0.0, 90.0, altitudeM = 3000.0),
        )
        val found = Cpa.notableApproaches(tracks)
        assertTrue(found.isNotEmpty())
        assertTrue(
            "a stationary contact must never appear",
            found.none { it.a.id == "PARKED" || it.b.id == "PARKED" },
        )
        // Ordered soonest first.
        val times = found.map { it.secondsToClosest }
        assertEquals(times.sorted(), times)
        // The pair genuinely closing on each other is in there.
        assertTrue(found.any { setOf(it.a.id, it.b.id) == setOf("NEAR_A", "NEAR_B") })

        // Every reported approach respects the time horizon it was asked for.
        assertTrue(Cpa.notableApproaches(tracks, withinSeconds = 10.0).all { it.secondsToClosest <= 10.0 })
        assertTrue(Cpa.notableApproaches(tracks, limit = 1).size <= 1)
        assertTrue(Cpa.notableApproaches(listOf(tracks.first())).isEmpty())
    }

    @Test fun theAdsbUnitConversionsAreRight() {
        // ADS-B reports knots and feet per minute; the geometry above is metric throughout.
        assertEquals(231.4998, Cpa.knotsToMs(450.0), 1e-3)
        assertEquals(6.0960, Cpa.feetPerMinuteToMs(1200.0), 1e-4)
        assertEquals(0.0, Cpa.knotsToMs(0.0), 1e-9)
        assertEquals(-6.0960, Cpa.feetPerMinuteToMs(-1200.0), 1e-4)
    }
}
