#!/usr/bin/env bash
# Compile the WHOLE nutrition application against the real Android platform classes.
#
# ⚠️ **This exists because its absence cost a CI round on a one-line Compose mistake.**
# `Arrangement.spacedBy(space, alignment)` takes an `Alignment.Horizontal`; I passed
# `Alignment.SpaceBetween`, which is an `Arrangement.Horizontal` — a different type — because I wrote
# the call from memory rather than from the declaration. Every gate in `check_changed.sh` passed it:
# the import gate saw `Alignment` imported and used, the enum-constant check only judges names
# declared in this repository, the parse gate does not resolve names at all, and the resolve gate
# looks at `app/` files. The Kotlin FRONTEND catches it in seconds, and that is what this runs.
#
# ⚠️ **A `@Composable` cannot be LOWERED without the Compose compiler plugin, and that is fine.**
# Kotlin compiles in two halves; reaching "Exception during IR lowering" proves the frontend — every
# name, every signature, every argument type — already passed. `android_compile_check.sh` knows the
# difference and reports it as a pass, so a screen full of composables is checkable here.
#
# What it does NOT do, so a clean run is not read as more than it is:
#   - it does not run the Compose compiler plugin, so a `@Composable`-only rule (reading a
#     composition local from a plain function) is still `tools/compose_local_check.py`'s job;
#   - it does not see resources, the manifest, R8 or anything AGP generates — `BuildConfig` is a stub
#     below, and a real one carrying a different type would not be caught;
#   - it does not draw a screen, open a camera or read a database.
#
# ⚠️ The two plain-JVM cores go on as COMPILED CLASSES, never as sources: passing sources folds them
# into one compilation unit, which makes them one module, which makes a cross-module smart cast — the
# error class that has broken this build three times — silently legal here while CI still rejects it.
# The three ANDROID library modules (`:core:health`, `:core:update`, `:core:scan`) cannot be built in
# this container at all, so their sources are folded in and a smart cast across those boundaries is
# invisible to this gate. That is the same trade `check_changed.sh` documents for `:core:database`.
set -uo pipefail
cd "$(dirname "$0")/.."

TCLASSES=core/telemetry/build/classes/kotlin/main
FCLASSES=core/feeds/build/classes/kotlin/main

# ⚠️ Rebuilt rather than assumed current. A stale class directory reports a member added to a core
# this hour as unresolved, which is indistinguishable from a real defect and has been read as one.
./gradlew :core:telemetry:classes :core:feeds:classes \
    --configure-on-demand --no-configuration-cache -q >/tmp/nutclasses.txt 2>&1
if [ ! -d "$TCLASSES" ] || [ ! -d "$FCLASSES" ]; then
    echo "COULD NOT BUILD the shared cores — this gate did not run:"
    tail -5 /tmp/nutclasses.txt
    exit 2
fi

# ⚠️ A stub, because `BuildConfig` is generated by AGP and does not exist in the source tree. It is
# read in one file, for the version it reports in a fault report and offers to the updater. Wrong
# here would mean a type mismatch this gate cannot see; the two fields are the ones AGP has always
# emitted and the real one is what CI compiles against.
STUB=/tmp/nutrition-stub
mkdir -p "$STUB"
cat > "$STUB/BuildConfig.kt" <<'EOF'
package dev.mascwa.nutrition
object BuildConfig {
    const val VERSION_NAME: String = "0"
    const val VERSION_CODE: Int = 0
}
EOF

SRC=$(find nutrition/src/main/java core/health/src/main core/update/src/main core/scan/src/main \
        -name '*.kt' 2>/dev/null)
SRC="$SRC $STUB/BuildConfig.kt core/database/src/main/java/dev/mascwa/pulse/data/food/db/FoodDatabase.kt"

# shellcheck disable=SC2086
OUT=$(bash tools/android_compile_check.sh -s -m "$TCLASSES" -m "$FCLASSES" \
    -l androidx.core:core:1.15.0 \
    -l androidx.core:core-ktx:1.15.0 \
    -l androidx.annotation:annotation-jvm:1.9.1 \
    -l androidx.annotation:annotation:1.9.1 \
    -l androidx.annotation:annotation-experimental:1.4.1 \
    -l androidx.savedstate:savedstate:1.2.1 \
    -l androidx.activity:activity:1.9.3 \
    -l androidx.activity:activity-compose:1.9.3 \
    -l androidx.lifecycle:lifecycle-common-jvm:2.8.7 \
    -l androidx.lifecycle:lifecycle-runtime-android:2.8.7 \
    -l androidx.lifecycle:lifecycle-runtime-ktx-android:2.8.7 \
    -l androidx.lifecycle:lifecycle-runtime-compose-android:2.8.7 \
    -l androidx.lifecycle:lifecycle-viewmodel-android:2.8.7 \
    -l androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7 \
    -l androidx.lifecycle:lifecycle-viewmodel-compose-android:2.8.7 \
    -l androidx.compose.runtime:runtime-android:1.7.6 \
    -l androidx.compose.runtime:runtime-saveable-android:1.7.6 \
    -l androidx.compose.ui:ui-android:1.7.6 \
    -l androidx.compose.ui:ui-text-android:1.7.6 \
    -l androidx.compose.ui:ui-graphics-android:1.7.6 \
    -l androidx.compose.ui:ui-unit-android:1.7.6 \
    -l androidx.compose.ui:ui-geometry-android:1.7.6 \
    -l androidx.compose.foundation:foundation-android:1.7.6 \
    -l androidx.compose.foundation:foundation-layout-android:1.7.6 \
    -l androidx.compose.material3:material3-android:1.3.1 \
    -l androidx.camera:camera-core:1.4.1 \
    -l androidx.camera:camera-camera2:1.4.1 \
    -l androidx.camera:camera-lifecycle:1.4.1 \
    -l androidx.camera:camera-view:1.4.1 \
    -l com.google.guava:guava:33.3.1-android \
    -l com.google.mlkit:barcode-scanning:17.3.0 \
    -l com.google.mlkit:vision-common:17.3.0 \
    -l com.google.mlkit:barcode-scanning-common:17.0.0 \
    -l com.google.mlkit:common:18.11.0 \
    -l com.google.android.gms:play-services-mlkit-barcode-scanning:18.3.1 \
    -l com.google.android.gms:play-services-basement:18.4.0 \
    -l com.google.android.gms:play-services-base:18.5.0 \
    -l com.google.mlkit:vision-interfaces:16.3.0 \
    -l com.google.android.gms:play-services-tasks:18.2.0 \
    -l com.google.zxing:core:3.5.3 \
    -l io.coil-kt:coil-compose:2.7.0 \
    -l io.coil-kt:coil-compose-base:2.7.0 \
    -l io.coil-kt:coil:2.7.0 \
    -l io.coil-kt:coil-base:2.7.0 \
    -l androidx.datastore:datastore-preferences-android:1.1.1 \
    -l androidx.datastore:datastore-preferences-core-jvm:1.1.1 \
    -l androidx.datastore:datastore-core-android:1.1.1 \
    -l androidx.datastore:datastore-core-okio-jvm:1.1.1 \
    -l androidx.health.connect:connect-client:1.1.0-beta01 \
    -l androidx.sqlite:sqlite:2.4.0 \
    -l androidx.room:room-runtime:2.6.1 \
    -l androidx.room:room-common:2.6.1 \
    -l org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.7.3 \
    -l com.squareup.okhttp3:okhttp:4.12.0 \
    $SRC 2>&1 | grep -vE '^curl:')

# ⚠️ Require a success line rather than treating quiet as clean. `android_compile_check.sh` has
# reported "compiles clean" having compiled nothing, and the output of a run that died before reading
# a line is indistinguishable from a pass.
#
# ⚠️ **BOTH phrasings, and the first version of this check accepted only one.** A tree of composables
# cannot reach the backend without the Compose plugin, so the honest answer here is "frontend clean";
# asking only for "compiles clean" reported a clean run as a failure. A gate that cries wolf on a
# passing tree is learnt to be ignored just as fast as one that stays quiet on a broken one.
if echo "$OUT" | grep -qE '^(compiles clean|frontend clean)'; then
    echo "$OUT" | grep -E '^(compiles clean|frontend clean)'
    exit 0
fi
echo "$OUT"
exit 1
