#!/usr/bin/env bash
# Is every screen on the PHONE findable, against the corpus it actually competes with?
#
# Extracts the SHIPPED literals (Directory, FeatureCatalog, SettingsCategory, the bundled guide
# index) on every run, then scores them with the SHIPPED GuideSearch/DeviceSearch/SettingsSections.
# Extracting each time is the point: a harness reading a checked-in snapshot can go stale against
# the source it claims to measure, and its silence would then mean nothing.
#
# ⚠️ The compiler's OWN -cp needs stdlib + trove4j + annotations + coroutines. Omit one and kotlinc
# dies in CoreApplicationEnvironment before reading a line — which looks exactly like a clean pass.
# So every jar is asserted, and so is the fact that classes came out.
set -euo pipefail
cd "$(dirname "$0")"
ROOT=$(cd ../.. && pwd)

python3 - "$ROOT" <<'PY'
import json, re, sys, pathlib
root = pathlib.Path(sys.argv[1])

def strip(src):
    out, i, n = [], 0, len(src)
    while i < n:
        if src.startswith('//', i):
            j = src.find('\n', i); i = j if j >= 0 else n; continue
        if src.startswith('/*', i):
            d = 0; j = i
            while j < n:
                if src.startswith('/*', j): d += 1; j += 2
                elif src.startswith('*/', j):
                    d -= 1; j += 2
                    if d == 0: break
                else: j += 1
            i = j; out.append(' '); continue
        out.append(src[i]); i += 1
    return ''.join(out)

def call_args(src, start):
    """The text inside a call whose '(' has just been consumed, quote- and paren-aware."""
    i, depth = start, 1
    while depth:
        c = src[i]
        if c == '"':
            i += 1
            while src[i] != '"': i += 2 if src[i] == '\\' else 1
        elif c == '(': depth += 1
        elif c == ')': depth -= 1
        i += 1
    return src[start:i - 1]

lits = lambda s: re.findall(r'"((?:[^"\\]|\\.)*)"', s)

# --- screens: the menu directory + the off-menu tabs -----------------------------------------
d = strip((root / 'app/src/main/java/dev/mascwa/pulse/navigation/Directory.kt').read_text())
entries = []
for m in re.finditer(r'MenuEntry\s*\(', d):
    body = call_args(d, m.end())
    lt, route = lits(body), re.search(r'Routes\.([A-Z_0-9]+)', body)
    if len(lt) >= 2 and route:
        entries.append((route.group(1), lt[0], lt[1], lt[2:]))

f = strip((root / 'app/src/main/java/dev/mascwa/pulse/data/usage/FeatureCatalog.kt').read_text())
off = [(m.group(1), m.group(2), m.group(3), []) for m in re.finditer(
    r'FeatureMeta\(\s*Routes\.([A-Z_0-9]+)\s*,\s*"((?:[^"\\]|\\.)*)"\s*,\s*"((?:[^"\\]|\\.)*)"', f)]

allr = off + entries
# ⚠️ Assert the extractor sees values known to be present, before its silence means anything.
assert any(l == 'Search Survival' for _, l, _, _ in allr), "menu entries not parsed"
assert any(l == 'Computer' for _, l, _, _ in allr), "off-menu tabs not parsed"
assert sum(1 for r in allr if r[3]) > 20, "synonym lists not parsed"

with open('features.tsv', 'w') as fh, open('terms.tsv', 'w') as tf:
    for route, label, desc, terms in allr:
        if route == 'SEARCH':      # the shipped index excludes it
            continue
        fh.write(f"{route}\t{label}\t{(desc + ' ' + ' '.join(terms)).strip()}\n")
        tf.write(f"{route}\t{' '.join(terms)}\n")

# --- guides: the real bundled index ------------------------------------------------------------
gi = json.loads((root / 'app/src/main/assets/survival/guide_index.json').read_text())['entries']
assert len(gi) > 800, f"only {len(gi)} guides"
with open('guides.tsv', 'w') as fh:
    for g in gi:
        fh.write("\t".join(x.replace('\t', ' ').replace('\n', ' ') for x in [
            g.get('id', ''), g.get('title', ''), g.get('category', ''),
            g.get('summary', '') or '', " ".join(g.get('headings', []) or []),
        ]) + "\n")

# --- stubs, GENERATED from the real declarations so the data cannot drift ----------------------
sc = (root / 'app/src/main/java/dev/mascwa/pulse/feature/settings/SettingsCategory.kt').read_text()
body = sc[sc.index('enum class SettingsCategory'):]
cats = []
for m in re.finditer(r'\n    ([A-Z_]+)\(', body):
    lt = lits(call_args(body, m.end()))
    if len(lt) >= 3:
        cats.append((m.group(1), lt[0], lt[1], lt[3] if len(lt) > 3 else ""))
assert len(cats) == 10, f"parsed {len(cats)} categories"
by = {c[0]: c for c in cats}
assert by['CONTENT'][1] == 'Content & feeds' and 'email' in by['CONTENT'][2] and by['SECURITY'][3]

esc = lambda s: s.replace('\\', '\\\\').replace('"', '\\"').replace('$', '\\$')
pathlib.Path('Routes.kt').write_text(
    "// GENERATED by run.sh from the real tree — do not hand-edit.\n"
    "package dev.mascwa.pulse.navigation\n\nobject Routes { const val SETTINGS = \"settings\" }\n")
pathlib.Path('Stubs.kt').write_text("\n".join(
    ["// GENERATED by run.sh from the real SettingsCategory.kt — do not hand-edit.",
     "package dev.mascwa.pulse.feature.settings", "",
     "enum class SettingsCategory(val title: String, val blurb: String, val keywords: String = \"\") {"]
    + [f'    {n}("{esc(t)}", "{esc(b)}", "{esc(k)}"),' for n, t, b, k in cats]
    + ["    ;", "}"]) + "\n")

print(f"extracted {len(allr)} screens, {len(gi)} guides, {len(cats)} settings categories from the real tree")
PY

G=/opt/gradle-8.14.3/lib
STD=$(ls $G/kotlin-stdlib-*.jar | head -1)
TROVE=$(ls $G/trove4j-*.jar | head -1)
ANN=$(ls $G/annotations-*.jar | head -1)
KC=$(ls $G/kotlin-compiler-embeddable-*.jar | head -1)
COR=$(find /root/.gradle/caches -name 'kotlinx-coroutines-core-jvm-*.jar' 2>/dev/null | head -1)
for j in "$STD" "$TROVE" "$ANN" "$KC" "$COR"; do
  [ -n "$j" ] && [ -f "$j" ] || { echo "MISSING JAR (the compiler would die before reading a line): $j"; exit 1; }
done
CORE=$ROOT/core/telemetry/src/main/java/dev/mascwa/pulse/core/telemetry
rm -rf out && mkdir -p out
java -cp "$KC:$STD:$TROVE:$ANN:$COR" org.jetbrains.kotlin.cli.jvm.K2JVMCompiler \
  "$CORE/GuideSearch.kt" "$CORE/DeviceSearch.kt" Routes.kt Stubs.kt \
  "$ROOT/app/src/main/java/dev/mascwa/pulse/feature/settings/SettingsSections.kt" Probe.kt \
  -cp "$STD" -d out -nowarn 2>&1 | grep -E '^(e:|error:)' && { echo "COMPILE FAILED"; exit 1; }
[ -f out/ProbeKt.class ] || { echo "NO CLASSES PRODUCED — the compiler did not run"; exit 1; }
java -cp "out:$STD" ProbeKt
