#!/usr/bin/env python3
"""Build the IAU 2000B nutation table the star map's true equinox of date is computed from.

Source: the IAU 2000A lunisolar nutation series as BUNDLED IN SKYFIELD (`skyfield/data/nutation.npz`,
read through `skyfield.nutationlib`, which is the NOVAS/SOFA table verbatim). IAU 2000B is the first
77 lunisolar terms of that series evaluated with LINEAR fundamental arguments, plus two constant
offsets standing in for the planetary series — exactly what `nutationlib.iau2000b` evaluates and what
SOFA's `iauNut00b` evaluates. Its own docstring says it agrees with the full 2000A model to a
milliarcsecond; the pins below measure that rather than quote it.

⚠️ Nothing here is typed from a book. The 77 rows, the five fundamental-argument polynomials and the
two planetary offsets are all READ OUT of the module at build time, and the builder then re-evaluates
its own emitted table with a plain scalar loop — the same arithmetic the Kotlin evaluator does — and
asserts agreement with `nutationlib.iau2000b` to a nanoarcsecond at 400 random instants over
1900–2100. A misread column, a swapped sin/cos, or a wrong unit cannot be emitted.

Output: Kotlin source for `internal object NutationTables` (one object, ~8 KB — nowhere near the JVM's
64 KB static-initialiser limit that shapes `Vsop87Tables`), and with `--pins` a JSON of
`(jdTT, dpsi_arcsec, deps_arcsec)` evaluated by BOTH `iau2000b` and `iau2000a`, for `NutationTest`.

Usage:
    PYTHONPATH=<skyfield install> python3 tools/sky/build_nutation.py [--out <NutationTables.kt>]
                                                                        [--pins <pins.json>]
Byte-reproducible: the same Skyfield version produces the same file.
"""
import argparse
import json
import math
import os
import random
import sys

import numpy as np
from skyfield import nutationlib as n

TERMS = 77                     # IAU 2000B: the first 77 lunisolar terms of IAU 2000A
ARGUMENT_TERMS = 2             # ... with LINEAR fundamental arguments (fa0 + fa1·t), as SOFA nut00b
ASEC360 = 1296000.0
ASEC2RAD = math.pi / 180.0 / 3600.0
TENTH_UAS = 1e-7               # the table is in tenths of a microarcsecond


def planetary_offsets():
    """The two constants iau2000b adds, read from its source rather than recalled."""
    import inspect
    src = inspect.getsource(n.iau2000b)
    dpsi = deps = None
    for line in src.splitlines():
        s = line.strip()
        if s.startswith("dpsi +="):
            dpsi = float(eval(s.split("+=", 1)[1]))
        elif s.startswith("deps +="):
            deps = float(eval(s.split("+=", 1)[1]))
    assert dpsi is not None and deps is not None, "iau2000b's planetary offsets not found in its source"
    return dpsi, deps


def fundamental_linear():
    """[[fa0_i, fa1_i] for i in l, l', F, D, Omega], arcseconds, straight from the module."""
    fa0 = np.asarray(n.fa0).reshape(5)
    fa1 = np.asarray(n.fa1).reshape(5)
    return [[float(fa0[i]), float(fa1[i])] for i in range(5)]


def table():
    mult = np.asarray(n.nals_t)[:TERMS]
    lon = np.asarray(n.lunisolar_longitude_coefficients)[:TERMS]
    obl = np.asarray(n.lunisolar_obliquity_coefficients)[:TERMS]
    assert mult.shape == (TERMS, 5) and lon.shape == (TERMS, 3) and obl.shape == (TERMS, 3)
    return mult, lon, obl


def evaluate(jd_tt, fund, mult, lon, obl, offsets):
    """The scalar loop the Kotlin side runs — a second implementation, so the emitted table is
    checked against Skyfield by arithmetic that shares nothing with Skyfield's vectorised one."""
    t = (jd_tt - 2451545.0) / 36525.0
    arg = [math.fmod(fund[i][1] * t + fund[i][0], ASEC360) * ASEC2RAD for i in range(5)]
    dpsi = deps = 0.0
    for k in range(TERMS):
        phi = sum(int(mult[k][i]) * arg[i] for i in range(5))
        s, c = math.sin(phi), math.cos(phi)
        dpsi += (lon[k][0] + lon[k][1] * t) * s + lon[k][2] * c
        deps += (obl[k][0] + obl[k][1] * t) * c + obl[k][2] * s
    return (dpsi + offsets[0]) * TENTH_UAS, (deps + offsets[1]) * TENTH_UAS


def fmt(x):
    """A Kotlin double literal that round-trips exactly."""
    r = repr(float(x))
    if "e" in r or "E" in r:
        return r
    return r if "." in r else r + ".0"


def emit(fund, mult, lon, obl, offsets):
    out = []
    w = out.append
    w("// GENERATED by tools/sky/build_nutation.py — DO NOT EDIT BY HAND. Regenerate with:")
    w("//     PYTHONPATH=<skyfield> python3 tools/sky/build_nutation.py")
    w("//")
    w("// IAU 2000B nutation: the first 77 lunisolar terms of the IAU 2000A series (NOVAS/SOFA table, as")
    w("// bundled in Skyfield), evaluated with LINEAR Simon-1994 fundamental arguments, plus two constant")
    w("// offsets standing in for the planetary series — exactly SOFA's iauNut00b. Each term is")
    w("//   dpsi += (A + A'·t)·sin(phi) + A''·cos(phi),   deps += (B + B'·t)·cos(phi) + B''·sin(phi)")
    w("// with phi = m·(l, l', F, D, Omega) and t in Julian centuries of TT from J2000. Coefficients are in")
    w("// TENTHS OF A MICROARCSECOND, as the source table is; `Nutation` scales them once at the end.")
    w("//")
    w("// ⚠️ Only the linear part of each fundamental argument is emitted, on purpose: IAU 2000B is DEFINED")
    w("// with linear arguments (SOFA nut00b), and the pins NutationTest holds were computed that way. Adding")
    w("// the quadratic terms would make the evaluator disagree with its own reference by microarcseconds")
    w("// while looking more precise.")
    w('@file:Suppress("MagicNumber")')
    w("")
    w("package dev.mascwa.pulse.core.telemetry")
    w("")
    w("internal object NutationTables {")
    w(f"    const val TERMS = {TERMS}")
    w("")
    w("    /** Simon et al. (1994): l, l', F, D, Omega as `[i][0] + [i][1]·t`, arcseconds. */")
    w("    @JvmField")
    w("    val FUNDAMENTAL: Array<DoubleArray> = arrayOf(")
    for i in range(5):
        w(f"        doubleArrayOf({fmt(fund[i][0])}, {fmt(fund[i][1])}),")
    w("    )")
    w("")
    w("    /** Integer multipliers of (l, l', F, D, Omega), five per term, flattened. */")
    w("    @JvmField")
    w("    val MULTIPLIERS: IntArray = intArrayOf(")
    for k in range(TERMS):
        w("        " + ", ".join(str(int(v)) for v in mult[k]) + ",")
    w("    )")
    w("")
    w("    /** Longitude: A (sin), A' (sin, ×t), A'' (cos) per term, flattened, 0.1 µas. */")
    w("    @JvmField")
    w("    val LONGITUDE: DoubleArray = doubleArrayOf(")
    for k in range(TERMS):
        w("        " + ", ".join(fmt(v) for v in lon[k]) + ",")
    w("    )")
    w("")
    w("    /** Obliquity: B (cos), B' (cos, ×t), B'' (sin) per term, flattened, 0.1 µas. */")
    w("    @JvmField")
    w("    val OBLIQUITY: DoubleArray = doubleArrayOf(")
    for k in range(TERMS):
        w("        " + ", ".join(fmt(v) for v in obl[k]) + ",")
    w("    )")
    w("")
    w("    /** The planetary nutation, collapsed to the constants IAU 2000B specifies, 0.1 µas. */")
    w(f"    const val PLANETARY_LONGITUDE = {fmt(offsets[0])}")
    w(f"    const val PLANETARY_OBLIQUITY = {fmt(offsets[1])}")
    w("}")
    w("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..", "core", "telemetry", "src", "main",
        "java", "dev", "mascwa", "pulse", "core", "telemetry", "NutationTables.kt"))
    ap.add_argument("--pins", default=None)
    args = ap.parse_args()

    fund = fundamental_linear()
    mult, lon, obl = table()
    offsets = planetary_offsets()

    # Self-check: the scalar loop over the emitted numbers against Skyfield's own iau2000b.
    rng = random.Random(20260923)
    worst = 0.0
    for _ in range(400):
        jd = 2415020.5 + rng.random() * 73048.0  # 1900-01-01 .. 2100-01-01
        ours = evaluate(jd, fund, mult, lon, obl, offsets)
        ref = n.iau2000b(jd)
        ref = (float(ref[0]) * TENTH_UAS, float(ref[1]) * TENTH_UAS)
        worst = max(worst, abs(ours[0] - ref[0]), abs(ours[1] - ref[1]))
    assert worst < 1e-9, f"the scalar loop disagrees with nutationlib.iau2000b by {worst} arcsec"
    print(f"self-check: scalar loop vs skyfield iau2000b, worst {worst:.2e} arcsec over 400 instants")

    src = emit(fund, mult, lon, obl, offsets)
    with open(args.out, "w") as f:
        f.write(src)
    print(f"wrote {args.out} ({len(src)} bytes, {TERMS} terms)")

    if args.pins:
        # Pins at fixed instants: J2000, 1900, 1950, 2026, 2045, 2075, 2100 — plus the full 2000A value so
        # the test can state how far the B model sits from A rather than quote a docstring.
        jds = [2451545.0, 2415020.5, 2433282.5, 2461041.5, 2467980.5, 2478938.75, 2488069.5]
        pins = []
        for jd in jds:
            b = n.iau2000b(jd)
            a = n.iau2000a(jd)
            pins.append({
                "jdTT": jd,
                "b": [float(b[0]) * TENTH_UAS, float(b[1]) * TENTH_UAS],
                "a": [float(a[0]) * TENTH_UAS, float(a[1]) * TENTH_UAS],
            })
        with open(args.pins, "w") as f:
            json.dump(pins, f, indent=1)
        gap = max(max(abs(p["a"][0] - p["b"][0]), abs(p["a"][1] - p["b"][1])) for p in pins)
        print(f"wrote {args.pins}; worst B-vs-A gap at the pins {gap * 1000:.3f} mas")


if __name__ == "__main__":
    main()
